// Animated nixmac mascot — real Lottie.
//
// Renders nixmac-mascot.json (generated by build_lottie.py) through lottie-web.
// This is a portable Lottie: the same .json plays in lottie-web, iOS/Android
// Lottie, and on LottieFiles — not just in React.
//
//   bun add lottie-react
//
// Needs `resolveJsonModule: true` in tsconfig (set in this app's tsconfig.json).
import Lottie, { type LottieRefCurrentProps } from "lottie-react";
import { useEffect, useRef } from "react";
import animationData from "./nixmac-mascot.json";

interface NixmacMascotLottieProps {
  /** Rendered square size in px. Default 160. */
  size?: number;
  loop?: boolean;
  autoplay?: boolean;
  /** Playback rate; >1 is faster. Handy to surface the intermittent hop quickly. */
  speed?: number;
  className?: string;
}

export function NixmacMascotLottie({
  size = 160,
  loop = true,
  autoplay = true,
  speed,
  className,
}: NixmacMascotLottieProps) {
  const lottieRef = useRef<LottieRefCurrentProps>(null);

  useEffect(() => {
    if (speed != null) lottieRef.current?.setSpeed(speed);
  }, [speed]);

  return (
    <Lottie
      lottieRef={lottieRef}
      animationData={animationData}
      loop={loop}
      autoplay={autoplay}
      className={className}
      style={{ width: size, height: size }}
      aria-label="nixmac mascot"
    />
  );
}

