# safe
WEB_URL: nixmac.com
# safe
API_URL: api.nixmac.com
sops:
    age:
        - recipient: age1c2q5fm3l3gn2tgcs35xstu44mu2zyrft993ksljw5r3z4dzcqcfq6vtakn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByNnoxbitGZHEzM1JJazZL
            WGlYcmlDMU9KZXpLN3A2MVZPMlZEd2FaTFVBCkhFY09VWk1QanpUOVBVM1lBVExY
            WXhnaWVRL0orNXNUN2NDZXEzU3ZUcWcKLS0tIFhmVzF5RDBZVTgyVnFtdTdkeGx4
            aEM0MUdUMGZSTVB1cXFCZXpBbStnemMK84Y+AKVGcTezjVb5z8U4H+iDKeDwPjRo
            xtKSS8cBQYK7A6/vm59Dm47okAVe56Tmnsl05aNvQHW6BrICFFbqbA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zl7nsteyj8lzu0spgd9qav3fhkmekkjd30uzt69mpmxgrev3nq7s3jnreh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlRW8vSDEvTmxZK0VHdEw5
            Z3RWV3lOaGpaRUNMSGRwdm95M0RsNmZSVHlVCjZ2YzdvOG1WRzB6WEthRFhUMmVr
            cmtHSmxML0o0bDBtNlhmYUUzcWljaW8KLS0tIHVkUzBla3RpdDNTTDE0MVZJZUlr
            aE82SWk0MEdVeURpeE1qVTlvNlV0ZkEKhPdK/SbRtrVeVSmkhWZlyzBn9Ie2D2I6
            qSMfmZ7fLWFwQifzXBGTzFmOA3/M/9UoQjhUDvd4KQgluhwiFVaLfw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age16wuzuxnkcgfuxzvzgk5e5a5f6hhs386adjewyv54m9esr4yj6uuslpn6tp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXdi8zTG5XUHlNNzJZaVli
            Wmd0UFl4eXNyTmFHUnVGTlRienovanVJNUZzCkFHZ3c5bDJ0SVJoU3pIUFlSZVRY
            TkdRVk9IWVEycGRjWlVibVRPQis2bkEKLS0tIGoyK1g0MWNMTTEzR0VzQU5rMkpP
            Y05EVjdqdmlHTHRHN0hFMklRNzRDbEUKeE7C4+QOyxqXtwSg0crBluxmGES2FvPD
            ThwwaoodtzLGP9gUWH+v3b4Js2Bo5oeJPVjttF3gt8PcZjcVnxClNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-16T01:48:08Z"
    mac: ENC[AES256_GCM,data:0SWFdQ/BvVdbZPQseeOU5HRuenOS4mhwcxYgg1nSMAA9haJ9zUWecjQ3UpzZQTv1fIyAoABbZDc6SBr7tXvHL567FFjCxTtVigg8pw9ZDlGgIUf7t0Kdo/yEzJT/M/gNyOBHO02tTnMGx3XFarZ/Cj8kU/IByz/93+j2UXXTrNw=,iv:rap4vuyishmZAc26eyz1/ZXNO+//F4qHdI8P77J1u8o=,tag:WvfaPfWLYOqxz4heUpCMBw==,type:str]
    unencrypted_comment_regex: ^\s?(safe|unencrypted)$
    version: 3.12.2
