//! Nix-related documentation used by the app that we source from statically bundled files.
//!
//!
use anyhow::Result;

use crate::docs::docs_system::{DocsIndex, DocsIndexLoader, initialize_docs_index_from_strs};

/// The nix-darwin docs JSON is generated by a script that extracts option paths, summaries, and types from the nix-darwin manual.
/// These are included in the app as static strings for simplicity and speed of access as well as for cases
/// where we're unable or unwilling to generate the "dynamic" docs specific to the user's nix environment using nix-eval.
/// The search_docs tool parses these JSONs into an in-memory index on first use,
/// then performs in-memory scoring and ranking of results for each query.
pub(crate) const NIX_DARWIN_DOCS_JSON: &str = include_str!("../../resources/nix-darwin-docs.json");
pub(crate) const HOME_MANAGER_DOCS_JSON: &str =
    include_str!("../../resources/home-manager-docs.json");

/// Loader for the bundled docs shipped with the app.
///
/// This is the guaranteed fast fallback. It never touches Nix or the filesystem
/// outside bundled resources, so `search_docs` can initialize immediately even
/// before generated docs have been cached.
pub struct StaticDocsIndexLoader;

impl StaticDocsIndexLoader {
    /// Construct the zero-state static loader.
    pub fn new() -> Self {
        Self
    }
}

impl DocsIndexLoader for StaticDocsIndexLoader {
    /// Parse bundled compact docs JSON into the shared in-memory index.
    fn load(&self) -> Result<DocsIndex> {
        initialize_docs_index_from_strs(NIX_DARWIN_DOCS_JSON, HOME_MANAGER_DOCS_JSON)
    }
}
