export {
  initialViewModelState,
  selectChangeMap,
  selectEvolve,
  selectEvolveEvents,
  selectExternalBuildDetected,
  selectGit,
  selectHistory,
  selectHosts,
  selectNixInstall,
  selectPermissions,
  selectPermissionsHydrated,
  selectPreferences,
  selectPromptHistory,
  selectRebuildLog,
  selectRebuildStatus,
  useViewModel,
  viewModelActions,
  viewModelStore,
  type RebuildLog,
  type ViewModel,
  type ViewModelSelector,
  type ViewModelState,
} from "./viewmodel";

export {
  initialUiState,
  selectCommitMessageSuggestion,
  selectConsoleLogs,
  selectConversationalResponse,
  selectEditingFile,
  selectError,
  selectEvolutionTelemetry,
  selectEvolvePrompt,
  selectFeedbackOpen,
  selectFilesystemTargetSection,
  selectIsBootstrapping,
  selectIsGenerating,
  selectIsProcessing,
  selectIsSummarizing,
  selectProcessingAction,
  selectRecommendedPrompt,
  selectRebuildContext,
  selectRebuildPanelDismissed,
  selectSettingsActiveTab,
  selectSettingsOpen,
  selectShowFilesystem,
  selectShowHistory,
  uiActions,
  uiStore,
  useUiState,
  type ProcessingAction,
  type SettingsTab,
  type UiStateSelector,
  type UiStateValues,
} from "./ui";

export {
  initialOnboardingState,
  onboardingActions,
  onboardingStore,
  selectCelebrating,
  selectInferenceDeferred,
  selectTrackedCustomizations,
  selectViewingStep,
  useOnboarding,
  type OnboardingSelector,
  type OnboardingStateValues,
  type OnboardingStepId,
} from "./onboarding";

export type { InferenceConfig, InferenceMode } from "./onboarding-types";
