OPENAI_API_KEY: ENC[AES256_GCM,data:lVpoaFVG1raJVv/KcedjQRRZIHeP4Gy2Ut7dIQReOSnm76E8eoyLIxYkek94YzOsgtBXFMFKWYdloH6Z98a/Qv3IO6p7l4iwVGeMFTQ7GqZ7bgqeGT8I1971eEPW97Plj1Yj5/psa3ne/+rnCwRMhkkUO926s0ygjh1Fgab+gEk2nCD46HzTba8KsemFFD+hcGcLCifficidZT+rkjIDlhSXgSE=,iv:3eSpWYYA0tB1uwTn0EwChi1INuMLxbFT5T+OFroWkOM=,tag:54id3mIzEBBCvhZa6KIy0g==,type:str]
# safe
PORT: 3000
sops:
    age:
        - recipient: age1ua3n0xa25z5tnrhhkndmkpz9elwsxw5jzq89fwldwlcm6wxg9ddsaxksm4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpZkkxOW1SVjRwZjZ1Mkdh
            K3dNOEQrckRDTllDOHJlbWNIbnB0VFNVWFVRCmw5NS9wQmJmSDFTM0s5YkNBTW5L
            eTZXS2ZFZGpFT0QxMWIyUXdSNnhMU0kKLS0tIDVxNGhiSVJaam1QeUhrTi82aXNT
            NTNkQ25qOFp0c2toVW1KZlRIRlhGbmMKXupqFba+nyUhXBLgdqmoD0+01SEuoEEe
            6WC5NZy1LSqZdSDrKA713A0FxN2AdzGYRYV51EDgUY0VDOKKsB4VVA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1unp2wxu3h5t5up5zsnqurwac69v84vtuy8lllpdwf03gddc6xfws00nu2a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJMVNsV050T3hLdk5ic0tw
            MmxMbTdPYlFVNnZ4ODBnS0ErQnloamNmcVFrClBGbFJQVGMycXJXYzVBWEhYSU9P
            eXJ2M1l1dkZ3cTdpNW9kQXNCWEhzd2sKLS0tIGQwcHVNQkpXdUdCNjZkaUppUG9k
            OWdZNFdtZDdyOWJhdzN5UEtXREF2emsKlVCJDfir5tua1ufe23asJH0kZ+BFsl1O
            mtY82vFIGK/S8po/GT4FSbmNkw9OOpCV6O1rgbkuWbwJgdckpgCTnw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age164al9lamrv4ufza9wvg5g5kh863yenq0gdggyxujugxqlv00894spd6jj9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1dmVkbUtoMFdrZnJQTDA4
            QlBvY0JhblZUUXBiRlBwVWc5dkM5UEhYbFNzCkZZK3VIbDNqNmQ3NWFwNkVDSEZD
            N2gxeVJhZngyMWN3ajE0NjFKaHN5b00KLS0tIHNIdWorbm52N0JsbVF4YVVuVWNs
            cVRGMVpjdHFXb2NhZ3BYaHcwL0lUQ00K/KjnWLceKZiEY2fqj4kqqGBXnR4+/XZo
            yVKvX8SJ/8kJCPq3Juri/9fo4iBti1xKU0enJ7bcQFFBh9IECQXjug==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vapyvpjzqg8wdfay055s574qt0u6avtzv4ch7kv0epvtycpyjqzqk3m4yr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkaHFpVkgvSXBCQ3FFdkZV
            cWNhQ25zVDJSMnZGUVN3WlBpSlRWUW5aY20wCno2MDVEQ3FFU0lMOXgvS1F5Vll2
            UkR3YmY4aDByeXBBSlpxWUc1SWdkNWcKLS0tIDJyQ1hJVGl4VVp0Q2hhaVJLUzBk
            RUJEbEk4bUN0WEJoMjhhcGpKblh1dUkK0oVx4cep06FZbQaqysKN9gYRrgJzxTu+
            avQC5v/eV3w3pMJIL3dHsBzXjt6i9/u8o5IQM/I+vTzr6iSB2HDulA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1c2q5fm3l3gn2tgcs35xstu44mu2zyrft993ksljw5r3z4dzcqcfq6vtakn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBObUVlQzZCZGE3TC91QjU5
            QUFQN2dVRStLNlpoOGxhR1hwZ3VVUE1hRWpvCnVsc2dxdjVVK0c5RW02KzU2cWZ6
            S0puRnIyU2c0K3JmRXQvb1F5cVZTam8KLS0tIEs5eTNmR2NZS1lDT1V3U0RYTTQy
            T3RJRjAwN3lrakpJQ3lrQVFtMjFWZVEKfbvPHo6nzO/j3hEqryxoV1ZqotrvETcY
            C4rSgIYLe0loz7w98/KwGG6//QrFdwhePrf/iZCrEVZ6cVkgbmL4DQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-29T14:56:55Z"
    mac: ENC[AES256_GCM,data:Td3KmC6PWljORus46cs01IHGMNV9gVVD1o4hwrCbhrqo72E+kzbaPTp2+VPCKjvKeVA4d0DvmOh1TI0qDlojH3WEXDgpzN+GYD+cOH6tV/CEbRZoEWoHqiSNAH0JhC/jpcXGZPHijcRQeRMchLA4X0JNu9Gn3eUBzAc/Fysq/Ug=,iv:Omyk0WOvowAK+vp3EfB2v3ZuaEaDeuwxBNXLtTBKMz0=,tag:UlYNPf3HvEKXQ1oplFLasA==,type:str]
    unencrypted_comment_regex: ^\s?(safe|plaintext|unencrypted)$
    version: 3.11.0
