hello: ENC[AES256_GCM,data:qZRtErHpJxxn5MLj7GKok2ZIc0fLrz5/jJ42YlDWHVOxP6VSI1Kw7nC29eaw9w==,iv:ZrssE8Me/RS2G29P6r3MCsI+r/EAR0/Vh2nqrckYNhw=,tag:u4XNs+9P3IINDQ3DHwesuA==,type:str]
sops:
    age:
        - recipient: age1ua3n0xa25z5tnrhhkndmkpz9elwsxw5jzq89fwldwlcm6wxg9ddsaxksm4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAydmpJaXc1bzl6V01pOGVz
            cGRYV3pkV1JIWElxVElUaUZMRHlxTFlMNm44CnBMdnhNMGRHOXEzMUsreGdaNTBm
            N0J0UktEQ3R3cmxPVGVIZGszdW0vbDQKLS0tIExQNVNTTkViYVY3ZWRxWTdKVkEx
            WWY1Ky9vY2tMODByWXVWRzlaUkg4OFkKhvBjKaIXaZ0RhzN4t0PSfkpk1oAPU0vm
            XZ9ZIRvOOzySBVBsdy54q2IMj9fmSmX9nNsIPAz9Ipz2BKIliBhXzg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1unp2wxu3h5t5up5zsnqurwac69v84vtuy8lllpdwf03gddc6xfws00nu2a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVMnQ5czVGS29OTWZ4eHpQ
            MVdPRm13VEw3bktYVTVYdnUyZWU0QnpwakFvClJPNTJSYTZvOE5lcWlCWXgzWWNE
            VG8zWGVLdlcyeElYaHZsWE9jZ2ltL3cKLS0tIHNmcDBnbWpTcGxSMzRzdFllZmFD
            RkVydVRqSmxMVW10eDE2ZndJdGVUa0EK5t1wbSYl9b7YkjaVd6kwZtxbdTXYUqEM
            8Xqv0t5SXaa8r+quEV+IDdqckVoMqwx5164mywFevhNFDbkVgxTiZQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age164al9lamrv4ufza9wvg5g5kh863yenq0gdggyxujugxqlv00894spd6jj9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2REdEMkRjSWw5VG1XUG1h
            dm80OHpodXR1MlpnUGVTeGl4YzdrY1liNjI0CnRWampYeUI1RmJ6NWNuQkJuV29S
            MEFBVk5UcVVDUERtSDN4U213SFBuYWMKLS0tIEJIVUhORU43RlVVWk9rUEZVZ0lx
            dVJVaXl2cGQxYkJIdzRpSnZscUZNVmcK/PDJlv8XqGgGuGNa6kxI15xFJg40nrZG
            dnuX/1OENwGqnLOvrb/dKhNpZB8/V59MyvrcMAgTHxoX2DIlHHvi7g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vapyvpjzqg8wdfay055s574qt0u6avtzv4ch7kv0epvtycpyjqzqk3m4yr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBbU1PNE5TOEtSNmhSMWpv
            b0JTV3dmVWJrQi9PaXlNRUEvMklFL3R2dUFZCmRSMFVJS1R2VEFOREtlRXd1NWpD
            dnNZOGdKZkNYaS9TQks4NnA0ejc2bVkKLS0tIEFMMldwV0dHOEs2aGFJZ05pbXd6
            YTdJYjhZNFRhUGw3MWQxcW5VZE5PclUKBcpy3bqjkzn/cUJFcngy+4BQ3VrNtAeY
            hNi6Kkh5+qTvP+5WwaE8uSC0BSzEPqPY0A24QSwaOtpFNxVfeDGyjA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age16wuzuxnkcgfuxzvzgk5e5a5f6hhs386adjewyv54m9esr4yj6uuslpn6tp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMYitORkt6RVliNGJwOUZS
            Vk1vMjVLbTFIKzJIL3VoSDMzcTBMUDlFN1VnCnloWDdHdGxvQ3RzVzBDbi9Wclgz
            OG55OE51SHNDV1BFU3ErSy9iM2RGcnMKLS0tIHFncGJmZDMwalJScWtmZ3RlRVQ4
            dmpic2ErNTZiaTV4cG5pK3RlS2tuL28KZrc7WorBct4OplV9FtV2GxkRYp/ZuDGk
            kTyqcA6qgRgmHLZB9+Z2YTufU+1QtgTPnQSyg3VnoBDpq1ADDBAbkA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1eqcj2g0fdekj2wpqp4y0fg9c5myydjdt9zlr5scr0grk6fxszymqkpw5jf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoK25kSnN2Q1pscWtkQmlK
            MkFVSWhsNi9mVld3TTB1akN4UzArM2xSdGhrClZPY2RXeTNSNWpDeHAybWpBYlhs
            WjdBa0FzdlQzWUo3K3QxZFBJMVhHNlkKLS0tIFY0U3E3enF0cTIvTG1TL1E0amw3
            NDEyZlpubW5kWi94eTRwS0lZZkJRdk0KsxjYi2tSpgoQpRx7jhZaFpSh6F+5+Fxm
            DP8E+tPuwS34O/JCRZHjs6wREw6HGW8XTT2oktiKAxFqno4oM3BM4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-29T13:42:22Z"
    mac: ENC[AES256_GCM,data:prCCmfhh42WVpGStT/0Zv6OFit9PtrVwNC/DaWJK5pCnAl04Hv7TLSOdlA0eBtSUjNtYtlvSwOH2g96WqZyDGG9Dr28T5qE6I3+UlMgKCexpNx2blWBK4Yu+4g2ijPLupoQ+KXG6JKd8gBhjqxbpR9ixIYv2/27Ype1sIYop/Lc=,iv:TJ6ucCwTFX6SzKoDQX9KRZwsnmN7d7RVw0f3QDgYTvU=,tag:s1RttZMZIfHNUTqzYjXaEQ==,type:str]
    unencrypted_comment_regex: ^\s?(safe|plaintext|unencrypted)$
    version: 3.11.0
