hello: ENC[AES256_GCM,data:qZRtErHpJxxn5MLj7GKok2ZIc0fLrz5/jJ42YlDWHVOxP6VSI1Kw7nC29eaw9w==,iv:ZrssE8Me/RS2G29P6r3MCsI+r/EAR0/Vh2nqrckYNhw=,tag:u4XNs+9P3IINDQ3DHwesuA==,type:str]
sops:
    age:
        - recipient: age1ua3n0xa25z5tnrhhkndmkpz9elwsxw5jzq89fwldwlcm6wxg9ddsaxksm4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLdmxReE8zZ1Jwb0VCQkxE
            VDA1a1l1bWhmR2Y4MWNFOWJHamxtdTVqZHpjClRDVTl5b3N1am9RQWwyZGZUcmI3
            VVUya0kyOTdTa1JlZXJpelMxYjRGYTgKLS0tIGM5clQwSnhYbksyK2lKcnE5MmpX
            dHAyakU2NzNTMXVIWjNsZEo0Z2xCTUUKTBmYN95Ns5amMZgJs5SwdF9EHR037xxn
            5eaZKX89N971b3lgB9laNEs1eQFM/j4c5aGEn884TQVVVzgqMZ2FuA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1unp2wxu3h5t5up5zsnqurwac69v84vtuy8lllpdwf03gddc6xfws00nu2a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvRlFRRVprbDk4Y3BpQUhF
            dUU0Z0ljTFlRUWJUVW9GR2N6SHloaUVCVXlNCmJzQmFXUFQ2elFxOG1JMFNiK0do
            eXU2cS83R0NvWW1qZFVEOUR1V0NvTTAKLS0tIHlhMzYvaENZbkFBaEYwYlpvbkJh
            QXNCOStLSXQvVUpqTjNCZ0NuWVkwbU0KjuE95NQkZzd5lHbs+S7ONHORsoTVWiTl
            QFJWw05Nq2reEsMTgMcx+9EarkwXxPjhSRPjTrT+MaN9Zss+w0s94Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age164al9lamrv4ufza9wvg5g5kh863yenq0gdggyxujugxqlv00894spd6jj9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSNEZjMFI5c1BDblY0T0xZ
            MjZlQ2tXZmYwOGtudEs2MWNIZGU0R0F3bmhVCkgwdXhVMW80MEN6SlRuRTNQRVd1
            QjM0VEs3VXdGbTZ0ZUdKUVl0L2YzeFkKLS0tIHd6cHZ4Wjd1TW5WYkFBK0pVSmQ3
            aURzck5ldlZXRXhjWWFoSGI3VWxIWGcKuL2WqrkJrKsyyuhmrdJPENJ5bhRK0SZq
            iI8utNjkWGUAewvcU6EK+rANtdBOHaqGZCdkfKhN+KGl+FKAn+Hw4w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vapyvpjzqg8wdfay055s574qt0u6avtzv4ch7kv0epvtycpyjqzqk3m4yr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHTVczN2MyZk0zZ3hFNk9t
            eUVmM0RsZGRuVlVoSE1MS2RHWFRSMzRTNEdZCnNhK3ZRci9IOWJ2ZzN1VWFreExk
            c0xoSTZWQUwzRGNmSUlLeWIrVHhOTTAKLS0tIFYvY1FEZDY0WlNoNGpubXlvNE55
            NjdzbjFpM0gzVlBLVlRyNXdpOTUrYjAKuZaujBIkBA5U5fUlZVi3BjiiZV+XEO6C
            qNhMA9953ncyDPWZIi+X5CRyE4T2daXckip/Ihn10uPgNEWr4ayd2Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age16wuzuxnkcgfuxzvzgk5e5a5f6hhs386adjewyv54m9esr4yj6uuslpn6tp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHQ29semRubllJaUExOGxy
            YUFrNTUxQlBuKzByby9xeUd6NVF4WjdNTGxVCkg0dk9nOWN6YWkxOVV5aHdQVzFE
            eDltYXhnWERlU09hTFdjbVp0b2poMXMKLS0tIDFRUEwzNTgvVWpGckVSSmNMV2xy
            ZGN3ZWVtdU41Z1BCTXAvMm8zenFqMzgKaZaFJTMKqE2TsOzPlE5MiBs5mgJlXUzv
            Dv/F0LTWRi871w4Y/fguU1mf+nLfvJ8E2MMXBlWkYzpvYdPijKd+3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-29T13:42:22Z"
    mac: ENC[AES256_GCM,data:prCCmfhh42WVpGStT/0Zv6OFit9PtrVwNC/DaWJK5pCnAl04Hv7TLSOdlA0eBtSUjNtYtlvSwOH2g96WqZyDGG9Dr28T5qE6I3+UlMgKCexpNx2blWBK4Yu+4g2ijPLupoQ+KXG6JKd8gBhjqxbpR9ixIYv2/27Ype1sIYop/Lc=,iv:TJ6ucCwTFX6SzKoDQX9KRZwsnmN7d7RVw0f3QDgYTvU=,tag:s1RttZMZIfHNUTqzYjXaEQ==,type:str]
    unencrypted_comment_regex: ^\s?(safe|plaintext|unencrypted)$
    version: 3.11.0
