OPENAI_API_KEY: ENC[AES256_GCM,data:lVpoaFVG1raJVv/KcedjQRRZIHeP4Gy2Ut7dIQReOSnm76E8eoyLIxYkek94YzOsgtBXFMFKWYdloH6Z98a/Qv3IO6p7l4iwVGeMFTQ7GqZ7bgqeGT8I1971eEPW97Plj1Yj5/psa3ne/+rnCwRMhkkUO926s0ygjh1Fgab+gEk2nCD46HzTba8KsemFFD+hcGcLCifficidZT+rkjIDlhSXgSE=,iv:3eSpWYYA0tB1uwTn0EwChi1INuMLxbFT5T+OFroWkOM=,tag:54id3mIzEBBCvhZa6KIy0g==,type:str]
# safe
PORT: 3000
sops:
    age:
        - recipient: age1ua3n0xa25z5tnrhhkndmkpz9elwsxw5jzq89fwldwlcm6wxg9ddsaxksm4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaTjZTNzRMVjY4aTdzMWJ5
            MmhDaVkvUUY3SlBNc0U1VVRyVmdPdHd5dmxjClRrZmhOYnhJWEQrT1I4WjRJVUc4
            blJySXNHTWNxcnJSWU5sbHpZUHlrMkkKLS0tIGxoYlJ4aDVueFpxU2UyaEdCNkdU
            ck1lcThBMEtlNEtXRC9aUnpkVmErb3MKi7uP0zRznwb1fTBliHWA8HlapJ9DEfYg
            9W//sj+zMP9QDMMdPvRAb0+ogerMEakwZ/5XVdwN+sdmF7ahrP965Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1unp2wxu3h5t5up5zsnqurwac69v84vtuy8lllpdwf03gddc6xfws00nu2a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4N0p0TXhqV3dUTzZ2Y2xa
            MTB2QVBVZVdFOGJNdzAyMDJEOEt4amFPclQ4CkdQZWVZcTZscU9SZ292bFJ4ZUN1
            RXJITEI4OXpUMndVNzZCV3N1N0RNaGMKLS0tIGs1ZVVjMEVFUHA2S1lERFFzRHNy
            K1ZCbm92MzV0Tk1qV0VqbE9PRzB0MzAK332uJt2KWs0C/elNUHk526JcFNhOcSP7
            9a/jSmaPEKHSBBwvG2oIyTvPxF4BlijNx8YbABtiEkGIB64Eok2SBw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age164al9lamrv4ufza9wvg5g5kh863yenq0gdggyxujugxqlv00894spd6jj9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuN3pqWDlxRUp3K2hDUHVD
            aHd1NlZQODF5dWFDZnlZcXQyREFkKzZ2cWc0CjlvMDIxRm1uWlpiSFBjeWNwaWs1
            ekRUNEtmQVIrenlaMGdtTkNGVFZMbGMKLS0tIE9rcEEycHJraTY2MXdrTVFNcE9j
            cUFtbDIyQTZ3V0pHZEZWcVZKekNVaWsKVcTdS4NoydqwBOzkqut8Arxd/hOJ4rID
            DrguMpG4oQAKcKPQ+gn9s3zB+/Be1lPbqaXans/G0SXtjx93C6wPxQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vapyvpjzqg8wdfay055s574qt0u6avtzv4ch7kv0epvtycpyjqzqk3m4yr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMUC9yeWNuWTJsTHFxTjNF
            MTlZWEVuWjlZYTRiOXc5YUpUaEJ4ZVZ1RGlJCmw5a3lXMVEwMFRLSmVZZzYvdHhM
            dGFTMEErUEVYcWFnSGpOZUFMcmQ4QU0KLS0tIFR1aWZqRENiZHBpSkZJSVFiZDB1
            eDcxZVpFY1o3ZTd4Q2Z2UjUwVnh5S3cKM+8fXNMei8rWxys7YXkjzb7vOfa09+e+
            Fyktu2uqUTF2256lvHg6llSRBHH0ttNNf4Rg9VMkopW3fN4ECjfISQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-29T14:56:55Z"
    mac: ENC[AES256_GCM,data:Td3KmC6PWljORus46cs01IHGMNV9gVVD1o4hwrCbhrqo72E+kzbaPTp2+VPCKjvKeVA4d0DvmOh1TI0qDlojH3WEXDgpzN+GYD+cOH6tV/CEbRZoEWoHqiSNAH0JhC/jpcXGZPHijcRQeRMchLA4X0JNu9Gn3eUBzAc/Fysq/Ug=,iv:Omyk0WOvowAK+vp3EfB2v3ZuaEaDeuwxBNXLtTBKMz0=,tag:UlYNPf3HvEKXQ1oplFLasA==,type:str]
    unencrypted_comment_regex: ^\s?(safe|plaintext|unencrypted)$
    version: 3.11.0
