hello: ENC[AES256_GCM,data:qZRtErHpJxxn5MLj7GKok2ZIc0fLrz5/jJ42YlDWHVOxP6VSI1Kw7nC29eaw9w==,iv:ZrssE8Me/RS2G29P6r3MCsI+r/EAR0/Vh2nqrckYNhw=,tag:u4XNs+9P3IINDQ3DHwesuA==,type:str]
sops:
    age:
        - recipient: age1ua3n0xa25z5tnrhhkndmkpz9elwsxw5jzq89fwldwlcm6wxg9ddsaxksm4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDNGpOTVQzYXhRYWFlSDZn
            Z0NJVXdFeEF1K2VpL2I4TlBvcnN5WWgrK0ZFCkJRKzFEQWF2MVZTcWpEM3V3bmZ1
            aytldjBoZ0dHeW95YkhvbTk4K0FXNncKLS0tIDdsUzBXMWtxd0pZYWVWZHRUSDQw
            Z3A4RGV4cDYyd2xqNmdHa3NvVFY4b0UKySoDzqYLxFY+pmLFV5SwB4BDRIhsKvrf
            TlrpGizftMJM6A1GNRHCom5qukYLgVbk+TRqmvhb06nEXyQGvkCIVA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1unp2wxu3h5t5up5zsnqurwac69v84vtuy8lllpdwf03gddc6xfws00nu2a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFdzBreWNHNGEwRGxNWHBi
            YTR2U3VuMlRLK0xUMEZld1NsWjE0UE9oUGhjCi81dnU2Ykd6a1Zsang3ZEhubW1U
            UVhleGZmcHNVeDBsOXlwb25zcnl2ZE0KLS0tIEgyY3hBdDNkejJabExMTS9CSzlI
            UEFOWlBUWHZxUVhDRm8rS2RCTktnam8KP/xz2XjlzKTbd/NVHFUsAMC+QOf77Hip
            sgwXvX8B4IGBARaQ0dneYRCv6kSgS3DyKWQGgqjwxx2NbiTgqEgNig==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age164al9lamrv4ufza9wvg5g5kh863yenq0gdggyxujugxqlv00894spd6jj9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRTzZkeTR2anJOOTB2K0Jj
            UlhxV0VnK2txNFZCRkxqTjhTcTUrL1Z3QlRVCk9qWGY5SGNJY0FITEkxb3JheW5X
            NEdFMlltT08rclJtdWpGWFFVVmxvd2cKLS0tIENTRWlQWThZOGtaODhJRnlRaGJQ
            TUlZR0dtajVUMnROUlBkb25NbDROdTQK2q8wmgcsB03LtF1jfbeqRhbPAXKci6kw
            XiUfVe2lbTX8gaHyr7jrCjR4OjzTvOcaBMGBDIOCqV0/gSUXVrZWvA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vapyvpjzqg8wdfay055s574qt0u6avtzv4ch7kv0epvtycpyjqzqk3m4yr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJM2Q1dy9TaVN3bC9LMnhY
            QnQ3OWNuTVl3clBIaG5ibnBXVXFhNkdHd2xRCnluSlBjZUFIWmtJUjZkbzMxMDRN
            Rmw0M2M1bUw3dmhHYkJ3Mm5yOXRZNjgKLS0tIFdYZXJsTzc2bHMxQWd3Wms4cmh0
            NkxZTVdPM2cvV0xrVTJVc0krSXI3eDgK+Z1rNQIP2co+u/BOEC5LKlwcfVcDrleg
            k6e2SRJjPW19QohzH4+ur7MmgptwcIM1tE9HBpbzgDaNhVhLmzQ2Fw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age16wuzuxnkcgfuxzvzgk5e5a5f6hhs386adjewyv54m9esr4yj6uuslpn6tp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNejdScHJNOE5MMWxYemFY
            TVVqSTJ3cWtHQWw3WnUzcXVYMkFqWEdtOEdvCjZSdEV5anNEWTlYcGJVMU5RMktm
            WE1XY05iYWVnbU5PWFAwV09ySXJOR1EKLS0tIERlbmNjeFJTbXVaRjhEdDBZL1Vi
            d1p5NkJOZ1BwRFd1RUJibVlBQVhodFkK1SReGsoPBbmwwIR5X0GW7sVnNSCoCHu8
            dZbMdo9xJ5xTUPAWVBVhkNY+7YHf1BYXMcjhIWOYDwNmgyLI+E0F5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-29T13:42:22Z"
    mac: ENC[AES256_GCM,data:prCCmfhh42WVpGStT/0Zv6OFit9PtrVwNC/DaWJK5pCnAl04Hv7TLSOdlA0eBtSUjNtYtlvSwOH2g96WqZyDGG9Dr28T5qE6I3+UlMgKCexpNx2blWBK4Yu+4g2ijPLupoQ+KXG6JKd8gBhjqxbpR9ixIYv2/27Ype1sIYop/Lc=,iv:TJ6ucCwTFX6SzKoDQX9KRZwsnmN7d7RVw0f3QDgYTvU=,tag:s1RttZMZIfHNUTqzYjXaEQ==,type:str]
    unencrypted_comment_regex: ^\s?(safe|plaintext|unencrypted)$
    version: 3.11.0
