// Generated by stackpanel — do not edit manually.
import alchemy from "alchemy";
import { CloudflareStateStore } from "alchemy/state";
import Infra from "./src/index.ts";
// Register legacy custom-resource providers so pending deletions from
// earlier generated stacks can still be finalized after migrations.
import "./src/resources/ec2-instance.ts";
import "./src/resources/iam-instance-profile.ts";
import "./src/resources/iam-role.ts";
import "./src/resources/key-pair.ts";
import "./src/resources/security-group.ts";


const app = await alchemy("nixmac-infra", {
  stateStore: process.env.CLOUDFLARE_API_TOKEN
    ? (scope) =>
        new CloudflareStateStore(scope, {
          apiToken: alchemy.secret(process.env.CLOUDFLARE_API_TOKEN!),
        })
    : undefined,
});

// Import and run infra modules
const aws_secretsOutputs = (await import("./modules/aws-secrets/index.ts")).default;


// Sync declared outputs to storage backend
await Infra.syncAll({
"aws-secrets": {
  outputs: aws_secretsOutputs,
  syncKeys: ["kmsAliasName","kmsKeyArn","kmsKeyId","oidcProviderArn","roleArn","roleName"],
},
});

await app.finalize();
