// This file has been generated by Specta. DO NOT EDIT.

export type Change = { id: number; hash: string; filename: string; diff: string; lineCount: number; createdAt: number; groupSummaryId: number | null; ownSummaryId: number | null }

/**
 * Groups Changes for a commit→base_commit pair. `commit_id` is NULL for speculative
 * (uncommitted) changesets. Membership is stored in the `set_changes` join table.
 */
export type ChangeSet = { id: number; commitId: number | null; baseCommitId: number; commitMessage: string | null; generatedCommitMessage: string | null; createdAt: number }

export type ChangeSummary = { id: number; title: string; description: string; groupSummaryFor: string | null; createdAt: number }

/**
 * Result of a dirty-HEAD hash lookup.
 * `unsummarized_hashes` contains hashes with no stored match — these still need the pipeline.
 */
export type FoundChanges = { summarized: SummarizedChange[]; unsummarizedHashes: string[] }

export type SummarizedChange = { change: Change; ownSummary: ChangeSummary | null; groupSummary: ChangeSummary | null }

export type SummarizedChanges = { changeSet: ChangeSet; changes: SummarizedChange[] }

