// This file has been generated by Specta. DO NOT EDIT.

/**
 * Result of `darwin_build_check` — dry-run build outcome.
 */
export type BuildCheckResult = { passed: boolean; output: string }

export type Change = { id: number; hash: string; filename: string; diff: string; lineCount: number; createdAt: number; ownSummaryId: number | null }

/**
 * Groups Changes for a commit→base_commit pair. `commit_id` is NULL for speculative
 * (uncommitted) changesets. Membership is stored in the `set_changes` join table.
 */
export type ChangeSet = { id: number; commitId: number | null; baseCommitId: number; commitMessage: string | null; generatedCommitMessage: string | null; createdAt: number; evolutionId: number | null }

export type ChangeSummary = { id: number; title: string; description: string; 
/**
 * One of `"QUEUED"`, `"DONE"`, `"FAILED"`, `"CANCELLED"`.
 */
status: string; createdAt: number }

/**
 * Type of change for a file in git status.
 */
export type ChangeType = "new" | "edited" | "removed" | "renamed"

export type ChangeWithSummary = { id: number; hash: string; filename: string; diff: string; lineCount: number; createdAt: number; ownSummaryId: number | null; title: string; description: string }

/**
 * Availability of known AI CLI tools.
 */
export type CliToolsState = { claude: boolean; codex: boolean; opencode: boolean }

export type Commit = { id: number; hash: string; treeHash: string; message: string | null; createdAt: number }

/**
 * Result of a successful `git_commit` command.
 */
export type CommitResult = { hash: string; evolveState: EvolveState }

/**
 * Application configuration returned by `config_get`.
 */
export type Config = { configDir: string; hostAttr: string | null }

/**
 * Result of a managed-edit apply operation (homebrew, system-defaults, etc.).
 */
export type ConfigEditApplyResult = { ok: boolean; count: number; changeMap: SemanticChangeMap; gitStatus: GitStatus; evolveState: EvolveState }

/**
 * Result of a darwin-rebuild operation from the legacy non-streaming command.
 */
export type DarwinApplyLegacy = { ok: boolean; code: number | null; stdout: string | null; stderr: string | null }

/**
 * Response from the debug Sentry event command.
 */
export type DebugSentryResult = { ok: boolean; message: string }

/**
 * Evolution failure payload with partial telemetry.
 */
export type EvolutionFailureResult = { error: string; gitStatus: GitStatus | null; telemetry: EvolutionTelemetry }

/**
 * Evolution result returned to the frontend on completion.
 */
export type EvolutionResult = { changeMap: SemanticChangeMap; gitStatus: GitStatus; evolveState: EvolveState; conversationalResponse: string | null; telemetry: EvolutionTelemetry }

/**
 * Evolution lifecycle state.
 */
export type EvolutionState = 
/**
 * Initial state before generation starts
 */
"pending" | 
/**
 * Currently generating/processing
 */
"loading" | 
/**
 * Generation complete, ready for review
 */
"generated" | 
/**
 * Changes have been applied (darwin-rebuild ran)
 */
"applied" | 
/**
 * Changes have been committed
 */
"committed" | 
/**
 * An error occurred
 */
"failed" | 
/**
 * Agent responded conversationally without making any environment changes
 */
"conversational"

/**
 * Telemetry counters from a completed evolution run.
 */
export type EvolutionTelemetry = { state: EvolutionState; iterations: number; buildAttempts: number; totalTokens: number; editsCount: number; thinkingCount: number; toolCallsCount: number; durationMs: number }

/**
 * Acknowledgement from `darwin_evolve_cancel`.
 */
export type EvolveCancelResult = { ok: boolean; message: string }

/**
 * Event type for streaming evolve progress updates.
 */
export type EvolveEvent = { raw: string; summary: string; eventType: EvolveEventType; iteration: number | null; timestampMs: number }

/**
 * Types of evolve events for UI rendering.
 */
export type EvolveEventType = "start" | "iteration" | "thinking" | "reading" | "editing" | "buildCheck" | "buildPass" | "buildFail" | "toolCall" | "apiRequest" | "apiResponse" | "complete" | "error" | "info" | "summarizing" | "question"

/**
 * Persisted evolve state stored in `evolve-state.json`.
 */
export type EvolveState = { evolutionId: number | null; currentChangesetId: number | null; 
/**
 * current state verifyably built
 */
committable: boolean; 
/**
 * branch used to reset repo state on evolve failure
 */
backupBranch: string | null; 
/**
 * rollback values recover repo state and reapply nix store path
 */
rollbackBranch: string | null; rollbackStorePath: string | null; rollbackChangesetId: number | null; step: EvolveStep }

/**
 * Widget step derived from `EvolveState` fields.
 */
export type EvolveStep = "begin" | "evolve" | "commit" | "manualEvolve" | "manualCommit"

/**
 * AI provider/model info and usage signals.
 */
export type FeedbackAiProviderModelInfo = { evolveProvider: string | null; evolveModel: string | null; summaryProvider: string | null; summaryModel: string | null; totalTokens: number | null; latencyMs: number | null; iterations: number | null; buildAttempts: number | null }

/**
 * Flake input metadata captured from flake.lock.
 */
export type FeedbackFlakeInputEntry = { rev: string | null; lastModified: number | null; narHash: string | null }

/**
 * Snapshot of selected flake inputs.
 */
export type FeedbackFlakeInputsSnapshot = { nixpkgs: FeedbackFlakeInputEntry | null; "nix-darwin": FeedbackFlakeInputEntry | null; "home-manager": FeedbackFlakeInputEntry | null }

/**
 * Request payload for gathering feedback metadata.
 */
export type FeedbackMetadataRequest = { feedbackType: string; share: FeedbackShareOptions }

/**
 * Panic/crash information captured when a Rust panic occurs.
 */
export type FeedbackPanicDetails = { message: string; location: string | null; backtrace: string | null; timestamp: string }

/**
 * Options indicating which feedback artifacts the user allows sharing.
 */
export type FeedbackShareOptions = { currentAppState: boolean; systemInfo: boolean; usageStats: boolean; evolutionLog: boolean; changedNixFiles: boolean; aiProviderModelInfo: boolean; buildErrorOutput: boolean; flakeInputsSnapshot: boolean; appLogs: boolean }

/**
 * System information captured from the runtime.
 */
export type FeedbackSystemInfo = { osName: string | null; osVersion: string | null; arch: string | null; nixVersion: string | null; appVersion: string | null }

/**
 * File or directory entry returned by the editor tree.
 */
export type FileEntry = { path: string; name: string; isDir: boolean }

/**
 * Result of a successful `finalize_apply` or `finalize_rollback` command.
 */
export type FinalizeApplyResult = { gitStatus: GitStatus; evolveState: EvolveState }

/**
 * Individual file status parsed from diff headers.
 */
export type GitFileStatus = { path: string; changeType: ChangeType }

/**
 * Comprehensive git repository status.
 */
export type GitStatus = { files: GitFileStatus[]; branch: string | null; diff: string; additions: number; deletions: number; headCommitHash: string | null; cleanHead: boolean; changes: Change[] }

/**
 * A commit entry combining git log data, tag-derived flags, optional DB metadata, and raw diff changes.
 */
export type HistoryItem = { hash: string; message: string | null; createdAt: number; isBuilt: boolean; isBase: boolean; isExternal: boolean; fileCount: number; commit: Commit | null; changeMap: SemanticChangeMap | null; unsummarizedHashes: string[]; rawChanges: Change[]; originMessage: string | null; originHash: string | null; isOrphanedRestore: boolean; isUndone: boolean }

export type HomebrewState = { isInstalled: boolean; casks: string[]; brews: string[]; taps: string[]; source: string | null; lastChecked: number }

/**
 * Result of `nix_check` — reports whether Nix and darwin-rebuild are available.
 */
export type NixCheckResult = { installed: boolean; version: string | null; darwinRebuildAvailable: boolean }

/**
 * Generic acknowledgement returned by fire-and-forget commands.
 */
export type OkResult = { ok: boolean }

/**
 * Individual permission state.
 */
export type Permission = { id: string; name: string; description: string; required: boolean; canRequestProgrammatically: boolean; status: PermissionStatus; instructions?: string | null }

/**
 * Permission status.
 */
export type PermissionStatus = "granted" | "denied" | "pending" | "unknown"

/**
 * All permissions state.
 */
export type PermissionsState = { permissions: Permission[]; allRequiredGranted: boolean; checkedAt: number | null }

/**
 * State sent to the preview indicator window.
 */
export type PreviewIndicatorState = { visible: boolean; summary: string | null; filesChanged: number; additions: number | null; deletions: number | null; isLoading: boolean }

/**
 * A recommended prompt based on the user's current macOS settings.
 */
export type RecommendedPrompt = { id: string; promptText: string }

/**
 * Result returned from a rollback erase operation.
 */
export type RollbackResult = { gitStatus: GitStatus; evolveState: EvolveState; rollbackStorePath: string | null; rollbackChangesetId: number | null }

export type SemanticChangeGroup = { summary: ChangeSummary; changes: ChangeWithSummary[] }

export type SemanticChangeMap = { groups: SemanticChangeGroup[]; singles: ChangeWithSummary[]; unsummarizedHashes: string[] }

/**
 * Result returned when the config directory is set (typed or picked).
 * `evolve_state` and `hosts` are `Some` only when the directory actually changed.
 */
export type SetDirResult = { dir: string; evolveState: EvolveState | null; hosts: string[] | null }

export type SummarizedChange = { change: Change; ownSummary: ChangeSummary | null; groupSummary: ChangeSummary | null }

export type SummarizedChangeSet = { changeSet: ChangeSet; changes: SummarizedChange[]; missedHashes: string[] }

/**
 * A single macOS system default that differs from the factory value.
 */
export type SystemDefault = { nixKey: string; label: string; category: string; currentValue: string; defaultValue: string }

/**
 * Result of a full system defaults scan.
 */
export type SystemDefaultsScan = { defaults: SystemDefault[]; totalScanned: number }

/**
 * User interface preferences (synced to settings.json via tauri-plugin-store).
 */
export type UiPrefs = { openrouterApiKey: string | null; openaiApiKey: string | null; ollamaApiBaseUrl: string | null; vllmApiBaseUrl: string | null; vllmApiKey: string | null; summaryProvider: string | null; summaryModel: string | null; evolveProvider: string | null; evolveModel: string | null; maxIterations: number | null; maxBuildAttempts: number | null; sendDiagnostics: boolean; confirmBuild: boolean; confirmClear: boolean; confirmRollback: boolean; autoSummarizeOnFocus: boolean; scanHomebrewOnStartup: boolean; developerMode: boolean; pinnedVersion: string | null }

/**
 * Partial update to UI preferences — every field is optional so the caller
 * can send only the fields they wish to change.
 */
export type UiPrefsUpdate = { openrouterApiKey: string | null; openaiApiKey: string | null; evolveProvider: string | null; evolveModel: string | null; summaryProvider: string | null; summaryModel: string | null; maxIterations: number | null; maxBuildAttempts: number | null; ollamaApiBaseUrl: string | null; vllmApiBaseUrl: string | null; vllmApiKey: string | null; sendDiagnostics: boolean | null; confirmBuild: boolean | null; confirmClear: boolean | null; confirmRollback: boolean | null; autoSummarizeOnFocus: boolean | null; scanHomebrewOnStartup: boolean | null; developerMode: boolean | null; 
/**
 * `None` → field not sent; `Some(None)` → clear the pinned version.
 */
pinnedVersion?: string | null }

/**
 * Event payload emitted by the git status watcher.
 */
export type WatcherEvent = { gitStatus: GitStatus | null; changeMap: SemanticChangeMap | null; evolveState: EvolveState | null; error: string | null; externalBuildDetected: boolean }

