// This file has been generated by Specta. DO NOT EDIT.

export type Change = { id: number; hash: string; filename: string; diff: string; lineCount: number; createdAt: number; ownSummaryId: number | null }

/**
 * Groups Changes for a commit→base_commit pair. `commit_id` is NULL for speculative
 * (uncommitted) changesets. Membership is stored in the `set_changes` join table.
 */
export type ChangeSet = { id: number; commitId: number | null; baseCommitId: number; commitMessage: string | null; generatedCommitMessage: string | null; createdAt: number; evolutionId: number | null }

export type ChangeSummary = { id: number; title: string; description: string; 
/**
 * One of `"QUEUED"`, `"DONE"`, `"FAILED"`, `"CANCELLED"`.
 */
status: string; createdAt: number }

export type ChangeWithSummary = { id: number; hash: string; filename: string; diff: string; lineCount: number; createdAt: number; ownSummaryId: number | null; title: string; description: string }

/**
 * Persisted evolve state stored in `evolve-state.json`.
 */
export type EvolveState = { evolutionId: number | null; currentChangesetId: number | null; changesetAtBuild: number | null; committable: boolean; 
/**
 * Computed from the other fields — always kept in sync by `set`.
 */
step: EvolveStep }

/**
 * Widget step derived from `EvolveState` fields.
 */
export type EvolveStep = "begin" | "evolve" | "merge"

export type SemanticChangeGroup = { summary: ChangeSummary; changes: ChangeWithSummary[] }

export type SemanticChangeMap = { groups: SemanticChangeGroup[]; singles: ChangeWithSummary[]; missedHashes: string[] }

export type SummarizedChange = { change: Change; ownSummary: ChangeSummary | null; groupSummary: ChangeSummary | null }

export type SummarizedChangeSet = { changeSet: ChangeSet; changes: SummarizedChange[]; missedHashes: string[] }

