// This file has been generated by Specta. DO NOT EDIT.

export type Change = { id: number; hash: string; filename: string; diff: string; lineCount: number; createdAt: number; ownSummaryId: number | null }

/**
 * Groups Changes for a commit→base_commit pair. `commit_id` is NULL for speculative
 * (uncommitted) changesets. Membership is stored in the `set_changes` join table.
 */
export type ChangeSet = { id: number; commitId: number | null; baseCommitId: number; commitMessage: string | null; generatedCommitMessage: string | null; createdAt: number; evolutionId: number | null }

export type ChangeSummary = { id: number; title: string; description: string; 
/**
 * One of `"QUEUED"`, `"DONE"`, `"FAILED"`, `"CANCELLED"`.
 */
status: string; createdAt: number }

/**
 * Type of change for a file in git status.
 */
export type ChangeType = "new" | "edited" | "removed" | "renamed"

export type ChangeWithSummary = { id: number; hash: string; filename: string; diff: string; lineCount: number; createdAt: number; ownSummaryId: number | null; title: string; description: string }

export type Commit = { id: number; hash: string; treeHash: string; message: string | null; createdAt: number }

/**
 * Persisted evolve state stored in `evolve-state.json`.
 */
export type EvolveState = { evolutionId: number | null; currentChangesetId: number | null; changesetAtBuild: number | null; committable: boolean; backupBranch: string | null; 
/**
 * Computed from the other fields — always kept in sync by `set`.
 */
step: EvolveStep }

/**
 * Widget step derived from `EvolveState` fields.
 */
export type EvolveStep = "begin" | "evolve" | "merge"

/**
 * Individual file status parsed from diff headers.
 */
export type GitFileStatus = { path: string; changeType: ChangeType }

/**
 * Comprehensive git repository status.
 */
export type GitStatus = { files: GitFileStatus[]; branch: string | null; headIsBuilt: boolean; diff: string; additions: number; deletions: number; headCommitHash: string | null; cleanHead: boolean; changes: Change[] }

/**
 * A commit entry combining git log data, tag-derived flags, optional DB metadata, and raw diff changes.
 */
export type HistoryItem = { hash: string; message: string | null; createdAt: number; isBuilt: boolean; isBase: boolean; isExternal: boolean; fileCount: number; commit: Commit | null; changeMap: SemanticChangeMap | null; rawChanges: Change[] }

export type SemanticChangeGroup = { summary: ChangeSummary; changes: ChangeWithSummary[] }

export type SemanticChangeMap = { groups: SemanticChangeGroup[]; singles: ChangeWithSummary[]; missedHashes: string[] }

export type SummarizedChange = { change: Change; ownSummary: ChangeSummary | null; groupSummary: ChangeSummary | null }

export type SummarizedChangeSet = { changeSet: ChangeSet; changes: SummarizedChange[]; missedHashes: string[] }

/**
 * Event payload emitted by the git status watcher.
 */
export type WatcherEvent = { gitStatus: GitStatus | null; changeMap: SemanticChangeMap | null; evolveState: EvolveState | null; error: string | null }

