// This file has been generated by Specta. DO NOT EDIT.

export type Change = { id: number; hash: string; filename: string; diff: string; lineCount: number; createdAt: number; groupSummaryId: number | null; ownSummaryId: number | null }

/**
 * Groups Changes for a commit→base_commit pair. `commit_id` is NULL for speculative
 * (uncommitted) changesets. Membership is stored in the `set_changes` join table.
 */
export type ChangeSet = { id: number; commitId: number | null; baseCommitId: number | null; commitMessage: string; generatedCommitMessage: string | null; createdAt: number }

export type ChangeSummary = { id: number; title: string; description: string; groupSummaryFor: string | null; createdAt: number }

export type CommitRow = { id: number; hash: string; treeHash: string; message: string | null; createdAt: number }

export type EvolutionCommitRow = { evolutionId: number; commitId: number }

export type EvolutionRow = { id: number; branch: string; merged: number; builds: number }

export type PromptRow = { id: number; text: string; commitId: number | null; createdAt: number }

export type SquashedCommitRow = { targetId: number; sourceId: number }

export type SummaryRow = { id: number; commitId: number; baseCommitId: number | null; contentJson: string; diff: string; createdAt: number }

