// This file has been generated by Specta. DO NOT EDIT.

export type CommitRow = { id: number; hash: string; treeHash: string; message: string | null; createdAt: number }

export type EvolutionCommitRow = { evolutionId: number; commitId: number }

export type EvolutionRow = { id: number; branch: string; merged: number; builds: number }

export type PromptRow = { id: number; text: string; commitId: number | null; createdAt: number }

export type SquashedCommitRow = { targetId: number; sourceId: number }

export type SummaryRow = { id: number; commitId: number; baseCommitId: number | null; contentJson: string; diff: string; createdAt: number }

