/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodosRouteImport } from './routes/todos'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as Lp2RouteImport } from './routes/lp2'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrpcSplatRouteImport } from './routes/trpc.$'
import { Route as ApiSplatRouteImport } from './routes/api.$'

const TodosRoute = TodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const Lp2Route = Lp2RouteImport.update({
  id: '/lp2',
  path: '/lp2',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrpcSplatRoute = TrpcSplatRouteImport.update({
  id: '/trpc/$',
  path: '/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/login': typeof LoginRoute
  '/lp2': typeof Lp2Route
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/success': typeof SuccessRoute
  '/todos': typeof TodosRoute
  '/api/$': typeof ApiSplatRoute
  '/trpc/$': typeof TrpcSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/login': typeof LoginRoute
  '/lp2': typeof Lp2Route
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/success': typeof SuccessRoute
  '/todos': typeof TodosRoute
  '/api/$': typeof ApiSplatRoute
  '/trpc/$': typeof TrpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/login': typeof LoginRoute
  '/lp2': typeof Lp2Route
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/success': typeof SuccessRoute
  '/todos': typeof TodosRoute
  '/api/$': typeof ApiSplatRoute
  '/trpc/$': typeof TrpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/docs'
    | '/login'
    | '/lp2'
    | '/privacy-policy'
    | '/success'
    | '/todos'
    | '/api/$'
    | '/trpc/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/docs'
    | '/login'
    | '/lp2'
    | '/privacy-policy'
    | '/success'
    | '/todos'
    | '/api/$'
    | '/trpc/$'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/docs'
    | '/login'
    | '/lp2'
    | '/privacy-policy'
    | '/success'
    | '/todos'
    | '/api/$'
    | '/trpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  DocsRoute: typeof DocsRoute
  LoginRoute: typeof LoginRoute
  Lp2Route: typeof Lp2Route
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SuccessRoute: typeof SuccessRoute
  TodosRoute: typeof TodosRoute
  ApiSplatRoute: typeof ApiSplatRoute
  TrpcSplatRoute: typeof TrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/todos': {
      id: '/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof TodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lp2': {
      id: '/lp2'
      path: '/lp2'
      fullPath: '/lp2'
      preLoaderRoute: typeof Lp2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trpc/$': {
      id: '/trpc/$'
      path: '/trpc/$'
      fullPath: '/trpc/$'
      preLoaderRoute: typeof TrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  DocsRoute: DocsRoute,
  LoginRoute: LoginRoute,
  Lp2Route: Lp2Route,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SuccessRoute: SuccessRoute,
  TodosRoute: TodosRoute,
  ApiSplatRoute: ApiSplatRoute,
  TrpcSplatRoute: TrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
