export const NIXMAC_THEME = "nixmac-dark";

export const NIXMAC_THEME_DATA = {
  base: "vs-dark" as const,
  inherit: true,
  rules: [
    { token: "", foreground: "fafafa" },
    { token: "comment", foreground: "a3a3a3", fontStyle: "italic" },
    { token: "string", foreground: "23d0e7" },
    { token: "string.escape", foreground: "f7b23b" },
    { token: "keyword", foreground: "55a0f6" },
    { token: "keyword.control", foreground: "55a0f6" },
    { token: "keyword.operator", foreground: "a3a3a3" },
    { token: "constant", foreground: "f7b23b" },
    { token: "constant.language", foreground: "f7b23b" },
    { token: "constant.numeric", foreground: "f7b23b" },
    { token: "number", foreground: "f7b23b" },
    { token: "type", foreground: "55a0f6" },
    { token: "type.identifier", foreground: "55a0f6" },
    { token: "entity.name.function", foreground: "23d0e7" },
    { token: "entity.name.type", foreground: "55a0f6" },
    { token: "entity.name.tag", foreground: "f4587c" },
    { token: "support.function", foreground: "23d0e7" },
    { token: "variable.parameter", foreground: "f7b23b" },
    { token: "invalid", foreground: "f4587c" },
    { token: "addition.diff", foreground: "23d0e7" },
    { token: "deletion.diff", foreground: "f4587c" },
    { token: "info.diff", foreground: "a3a3a3" },
  ],
  colors: {
    "editor.background": "#0a0a0a",
    "editor.foreground": "#fafafa",
    "editorLineNumber.foreground": "#404040",
    "editorLineNumber.activeForeground": "#a3a3a3",
    "editor.selectionBackground": "#23d0e730",
    "editor.inactiveSelectionBackground": "#23d0e718",
    "editor.lineHighlightBackground": "#141414",
    "editorCursor.foreground": "#23d0e7",
    "editorGutter.background": "#0a0a0a",
    "editorGutter.addedBackground": "#23d0e740",
    "editorGutter.deletedBackground": "#f4587c40",
    "editorGutter.modifiedBackground": "#f7b23b40",
    "scrollbarSlider.background": "#26262680",
    "scrollbarSlider.hoverBackground": "#404040aa",
    "scrollbarSlider.activeBackground": "#555555aa",
    "editorWidget.background": "#141414",
    "editorWidget.border": "#262626",
    "diffEditor.insertedLineBackground": "#23d0e715",
    "diffEditor.removedLineBackground": "#f4587c15",
    "diffEditor.insertedTextBackground": "#00000000",
    "diffEditor.removedTextBackground": "#00000000",
    "diffEditorGutter.insertedLineBackground": "#00000000",
    "diffEditorGutter.removedLineBackground": "#00000000",
  },
};
