//! Top-level token generation for the `Configurable` derive. Parses the derive
//! tag and converts it into other rust code that in turn implements:
//!
//! - serialization and deserialization (serde)
//! - settings UI
//! - ability to save/load from disk
//!
//! The helpers in this module assemble already-parsed field and attribute data
//! into the generated `impl` block. Detailed attribute parsing and field type
//! mapping live in sibling modules so this file can read like the macro's
//! high-level pipeline.

use crate::attrs::{parse_struct_config, StoreScope};
use crate::fields::{generate_fields, named_fields, GeneratedFields};
use proc_macro2::TokenStream as TokenStream2;
use quote::quote;
use syn::DeriveInput;

/// Builds the full `impl` block generated by `#[derive(Configurable)]`.
///
/// `expand` is the macro's pipeline coordinator: it validates the input shape,
/// parses struct-level attributes, turns each field into reusable code
/// fragments, and then assembles those fragments into generated methods. It
/// should stay short enough that readers can see the derive's phases at a
/// glance; detailed parsing and token construction belongs in the helpers.
pub(crate) fn expand(input: DeriveInput) -> syn::Result<TokenStream2> {
    let name = &input.ident;
    let name_str = name.to_string();
    let struct_config = parse_struct_config(&input.attrs)?;
    let display_name = struct_config
        .display_name
        .clone()
        .unwrap_or_else(|| name_str.clone());
    let fields = generate_fields(named_fields(&input)?, &name_str)?;
    let methods = build_scope_methods(
        name,
        &name_str,
        &display_name,
        description_expr(struct_config.description.as_ref()),
        struct_config.scope,
        fields,
    );

    Ok(quote! {
        impl #name {
            #methods

            // Wry-specialized shims for the type-erased registry. Generic
            // functions can't be cast to fn pointers; these monomorphic
            // wrappers can.
            #[doc(hidden)]
            pub fn __configurable_schema_wry(
                app: &::tauri::AppHandle<::tauri::Wry>,
            ) -> ::std::result::Result<::configurable::ConfigurableSchema, ::anyhow::Error> {
                Self::schema(app)
            }

            #[doc(hidden)]
            pub fn __configurable_set_field_wry(
                app: &::tauri::AppHandle<::tauri::Wry>,
                key: &str,
                value: ::serde_json::Value,
            ) -> ::std::result::Result<(), ::anyhow::Error> {
                Self::set_field(app, key, value)
            }
        }
    })
}

/// Converts the optional struct description into generated code.
///
/// The generated methods build `ConfigurableSchema` at runtime, so even static
/// attribute strings need to become tokenized Rust expressions here.
fn description_expr(description: Option<&String>) -> TokenStream2 {
    match description {
        Some(s) => quote! { ::std::option::Option::Some(#s.to_string()) },
        None => quote! { ::std::option::Option::None },
    }
}

/// Emits the generated `load`, `schema`, and `set_field` methods.
///
/// All generated methods target the managed `Slice<T>` for the derived type.
/// That keeps persistence and UI change events behind the slice guard instead
/// of letting each configurable type choose its own storage path.
fn build_scope_methods(
    name: &syn::Ident,
    name_str: &str,
    display_name: &str,
    description_expr: TokenStream2,
    scope: StoreScope,
    fields: GeneratedFields,
) -> TokenStream2 {
    let scope_name = match scope {
        StoreScope::Global => "global",
        StoreScope::Repo => "repo",
    };
    let default_inits = fields.default_inits;
    let schema_fields = fields.schema_fields;
    let set_field_arms = fields.set_field_arms;

    // The derive is slice-only: reads mirror the managed slice, and writes go
    // through the slice guard so persistence and change events stay centralized.
    //
    // `load` can be called before startup finishes managing all slices, such as
    // in tests or early schema rendering. Defaults keep that path deterministic.
    quote! {
        pub fn load<R: ::tauri::Runtime>(
            app: &::tauri::AppHandle<R>,
        ) -> ::std::result::Result<Self, ::anyhow::Error> {
            if let ::std::option::Option::Some(__slice) =
                ::tauri::Manager::try_state::<crate::state::slice::Slice<#name>>(app)
            {
                return ::std::result::Result::Ok(__slice.read_sync().clone());
            }
            ::std::result::Result::Ok(Self {
                #(#default_inits)*
            })
        }

        pub fn schema<R: ::tauri::Runtime>(
            app: &::tauri::AppHandle<R>,
        ) -> ::std::result::Result<::configurable::ConfigurableSchema, ::anyhow::Error> {
            let __current = Self::load(app)?;
            ::std::result::Result::Ok(::configurable::ConfigurableSchema {
                name: #name_str.to_string(),
                display_name: #display_name.to_string(),
                description: #description_expr,
                fields: ::std::vec![
                    #(#schema_fields)*
                ],
            })
        }

        pub fn set_field<R: ::tauri::Runtime>(
            app: &::tauri::AppHandle<R>,
            key: &str,
            value: ::serde_json::Value,
        ) -> ::std::result::Result<(), ::anyhow::Error> {
            let __slice = ::tauri::Manager::try_state::<crate::state::slice::Slice<#name>>(app)
                .ok_or_else(|| ::anyhow::anyhow!(
                    "Configurable {}: {} slice is not managed",
                    #name_str, #scope_name,
                ))?;
            let mut __state = __slice.write_sync(app);
            match key {
                #(#set_field_arms)*
                other => ::std::result::Result::Err(::anyhow::anyhow!(
                    "Configurable {}: unknown field `{}`",
                    #name_str, other,
                )),
            }
        }
    }
}
