//! Top-level token generation for the `Configurable` derive. Parses the derive
//! tag and converts it into other rust code that in turn implements:
//!
//! - serialization and deserialization (serde)
//! - settings UI
//! - ability to save/load from disk
//!
//! The helpers in this module assemble already-parsed field and attribute data
//! into the generated `impl` block. Detailed attribute parsing and field type
//! mapping live in sibling modules so this file can read like the macro's
//! high-level pipeline.

use crate::attrs::{StoreScope, parse_struct_config};
use crate::fields::{GeneratedFields, generate_fields, named_fields};
use proc_macro2::TokenStream as TokenStream2;
use quote::quote;
use syn::DeriveInput;

/// Builds the full `impl` block generated by `#[derive(Configurable)]`.
///
/// `expand` is the macro's pipeline coordinator: it validates the input shape,
/// parses struct-level attributes, turns each field into reusable code
/// fragments, and then assembles those fragments into generated methods. It
/// should stay short enough that readers can see the derive's phases at a
/// glance; detailed parsing and token construction belongs in the helpers.
pub(crate) fn expand(input: DeriveInput) -> syn::Result<TokenStream2> {
    let name = &input.ident;
    let name_str = name.to_string();
    let struct_config = parse_struct_config(&input.attrs)?;
    let display_name = struct_config
        .display_name
        .clone()
        .unwrap_or_else(|| name_str.clone());
    let fields = generate_fields(named_fields(&input)?)?;
    let methods = build_scope_methods(
        name,
        &name_str,
        &display_name,
        description_expr(struct_config.description.as_ref()),
        struct_config.scope,
        fields,
    );

    Ok(quote! {
        impl #name {
            #methods

            // Wry-specialized shims for the type-erased compile-time registry.
            // Generic functions can't be cast to fn pointers; these monomorphic
            // wrappers can.
            #[doc(hidden)]
            pub fn __configurable_schema_wry() -> ::configurable::ConfigurableSchema {
                Self::schema()
            }

            #[doc(hidden)]
            pub fn __configurable_load_wry(
                app: &::tauri::AppHandle<::tauri::Wry>,
            ) -> ::std::result::Result<::serde_json::Value, ::anyhow::Error> {
                let __current = Self::load(app)?;
                ::std::result::Result::Ok(::serde_json::to_value(&__current)?)
            }

            #[doc(hidden)]
            pub fn __configurable_set_wry(
                app: &::tauri::AppHandle<::tauri::Wry>,
                value: ::serde_json::Value,
            ) -> ::std::result::Result<(), ::anyhow::Error> {
                Self::set(app, value)
            }
        }

        // Push this configurable into the inventory collection so
        // `inventory::iter::<ConfigurableMeta>()` enumerates it at runtime.
        ::configurable::inventory::submit! {
            ::configurable::ConfigurableMeta {
                name: #name_str,
                schema_fn: #name::__configurable_schema_wry,
                load_fn: #name::__configurable_load_wry,
                set_fn: #name::__configurable_set_wry,
            }
        }
    })
}

/// Converts the optional struct description into generated code.
///
/// The generated methods build `ConfigurableSchema` at runtime, so even static
/// attribute strings need to become tokenized Rust expressions here.
fn description_expr(description: Option<&String>) -> TokenStream2 {
    match description {
        Some(s) => quote! { ::std::option::Option::Some(#s.to_string()) },
        None => quote! { ::std::option::Option::None },
    }
}

/// Emits the generated `load`, `schema`, and `set` methods.
///
/// `schema` is intentionally context-free: it returns a `ConfigurableSchema`
/// built from the derive attributes alone, with no `AppHandle` involved. The
/// dev-settings command joins it with current values at the IPC boundary via
/// `load_value` so the static metadata stays cacheable.
///
/// `set` takes the whole struct as a single JSON payload. One Serde
/// deserialize validates every field at once; there is no per-field dispatch
/// table because the type system already knows the shape of `Self`.
fn build_scope_methods(
    name: &syn::Ident,
    name_str: &str,
    display_name: &str,
    description_expr: TokenStream2,
    scope: StoreScope,
    fields: GeneratedFields,
) -> TokenStream2 {
    let scope_name = match scope {
        StoreScope::Global => "global",
        StoreScope::Repo => "repo",
    };
    let default_inits = fields.default_inits;
    let schema_fields = fields.schema_fields;

    // The derive is observable-only: reads mirror the managed observable, and
    // writes go through the observable guard so persistence and change events
    // stay centralized.
    //
    // `load` can be called before startup finishes managing all observables,
    // such as in tests or early schema rendering. Defaults keep that path
    // deterministic.
    quote! {
        pub fn load<R: ::tauri::Runtime>(
            app: &::tauri::AppHandle<R>,
        ) -> ::std::result::Result<Self, ::anyhow::Error> {
            if let ::std::option::Option::Some(__observable) =
                ::tauri::Manager::try_state::<crate::observable::Observable<#name>>(app)
            {
                return ::std::result::Result::Ok(__observable.read_sync().clone());
            }
            ::std::result::Result::Ok(Self {
                #(#default_inits)*
            })
        }

        pub fn schema() -> ::configurable::ConfigurableSchema {
            ::configurable::ConfigurableSchema {
                name: #name_str.to_string(),
                display_name: #display_name.to_string(),
                description: #description_expr,
                fields: ::std::vec![
                    #(#schema_fields)*
                ],
            }
        }

        pub fn set<R: ::tauri::Runtime>(
            app: &::tauri::AppHandle<R>,
            value: ::serde_json::Value,
        ) -> ::std::result::Result<(), ::anyhow::Error> {
            let __observable =
                ::tauri::Manager::try_state::<crate::observable::Observable<#name>>(app)
                    .ok_or_else(|| ::anyhow::anyhow!(
                        "Configurable {}: {} observable is not managed",
                        #name_str, #scope_name,
                    ))?;
            let __next: Self = ::serde_json::from_value(value).map_err(|e| {
                ::anyhow::anyhow!("Configurable {}: invalid payload: {}", #name_str, e)
            })?;
            let mut __state = __observable.write_sync();
            *__state = __next;
            ::std::result::Result::Ok(())
        }
    }
}
