#!/usr/bin/env bash
#
# Free disk space on the persistent, self-hosted macOS CI runner.
#
# Unlike GitHub-hosted runners (a fresh VM per job), the self-hosted Mac keeps
# its disk across runs, so the Nix store, cargo target dir, and Tauri bundles
# accumulate until builds fail. The off-the-shelf "free disk space" actions
# target GitHub-hosted Ubuntu and do not apply here; this reclaims the things
# that actually grow on this runner.
#
# Usage:
#   free-disk-space.sh [--force] [min_free_gib]
#     (default)   clean only when free space < min_free_gib (default 25)
#     --force     always clean (scheduled maintenance)
#
# Env:
#   NIX_GC_AGE   age passed to `nix-collect-garbage --delete-older-than`
#                (default 3d). Age-bounded so recently cached closures (e.g.
#                the devenv profile) survive and need not be re-substituted.
#
# Never fails the calling job: best-effort cleanup, always exits 0.
set -uo pipefail

force=false
min_free_gib=25
for arg in "$@"; do
  case "$arg" in
    --force) force=true ;;
    *) min_free_gib="$arg" ;;
  esac
done

# Available GiB on the volume backing "$1" (-P: one line, -g: 1 GiB blocks).
avail_gib() {
  df -Pg "$1" 2>/dev/null | awk 'NR==2 {print $4}'
}

echo "== disk usage before cleanup =="
df -h . /nix 2>/dev/null || df -h .

free="$(avail_gib .)"
echo "free=${free:-unknown} GiB threshold=${min_free_gib} GiB force=${force}"

if [ "$force" != true ] && [ -n "${free:-}" ] && [ "${free}" -ge "${min_free_gib}" ]; then
  echo "Above threshold; nothing to do."
  exit 0
fi

# 1. Nix store — the biggest consumer. Age-bounded GC keeps recent closures.
if command -v nix-collect-garbage >/dev/null 2>&1; then
  echo "nix-collect-garbage --delete-older-than ${NIX_GC_AGE:-3d}"
  nix-collect-garbage --delete-older-than "${NIX_GC_AGE:-3d}" || true
fi

# 2. Tauri bundles (DMGs / .app archives) — regenerated by every build.
rm -rf apps/native/src-tauri/target/release/bundle 2>/dev/null || true

# 3. Stale cargo artifacts, if cargo-sweep is available (safe: only removes
#    artifacts untouched for 7+ days, never the current build's).
if command -v cargo-sweep >/dev/null 2>&1; then
  cargo-sweep --time 7 apps/native/src-tauri 2>/dev/null || true
fi

echo "== disk usage after cleanup =="
df -h . /nix 2>/dev/null || df -h .

exit 0
