"use client";

import { Button } from "@/components/ui/button";
import { useCurrentStep, useWidgetStore } from "@/stores/widget-store";
import { FeedbackType } from "@/types/feedback";
import { Settings } from "lucide-react";

/**
 * Error message component - displays errors from store.
 * Filters out certain errors based on context (e.g., expected errors during setup).
 */
export function ErrorMessage() {
  const error = useWidgetStore((s) => s.error);
  const setError = useWidgetStore((s) => s.setError);
  const openFeedback = useWidgetStore((s) => s.openFeedback);
  const setSettingsOpen = useWidgetStore((s) => s.setSettingsOpen);
  const step = useCurrentStep();

  // Suppress expected errors during setup (no flake.nix yet)
  const isSuppressedError =
    (step === "setup" && error?.includes("Failed to list hosts: path")) ||
    (step === "evolving" && error?.includes("cancelled by user"));

  if (!error || isSuppressedError) {
    return null;
  }

  // Show settings CTA only for auth/key-related errors, not billing or server errors.
  // These messages are generated by friendly_provider_error() in Rust:
  // - Auth errors (401/403) contain "API key" → show "Open Settings"
  // - Billing errors (402) mention "credits"/"billing" → no Settings CTA
  //   (Settings can't fix a credits problem; the message itself directs to billing page)
  // - Server/rate-limit errors → no CTA
  const showSettingsCta = error.includes("API key");

  return (
    <div className="mx-auto max-w-2xl rounded-lg border border-red-500/30 bg-red-500/10 p-3 text-sm text-red-400">
      <div className="whitespace-pre-wrap break-words">{error}</div>
      <div className="mt-2 flex items-center gap-3">
        {showSettingsCta && (
          <Button
            type="button"
            variant="link"
            size="sm"
            className="h-auto gap-1 p-0 text-red-300 underline text-xs"
            onClick={() => {
              setSettingsOpen(true, "api-keys");
              setError(null);
            }}
          >
            <Settings className="h-3 w-3" />
            Open Settings
          </Button>
        )}
        <Button
          type="button"
          variant="link"
          size="sm"
          className="h-auto p-0 text-red-300 underline text-xs"
          onClick={() => openFeedback(FeedbackType.Error, error)}
        >
          Report Error
        </Button>
        <Button
          type="button"
          variant="link"
          size="sm"
          className="h-auto p-0 text-red-300 underline text-xs"
          onClick={() => setError(null)}
        >
          Dismiss
        </Button>
      </div>
    </div>
  );
}
