// Auto-generated by orpc-specta. Do not edit.
import type { Client } from "@orpc/client"

// Auto-generated by orpc-specta. Do not edit.

/**
 * Billing snapshot returned by `/api/billing/state` for onboarding and account UI.
 */
export type AccountBilling = { usage: BillingUsage; subscriptions: BillingSubscription[]; hasPaymentMethod: boolean; canUseHostedInference: boolean; canUseDeviceSync: boolean }

export type ActivateStorePathInput = { storePath: string }

export type AdoptManualChangesResult = { evolutionId: number }

export type ApplyDiffInput = { diff: HomebrewState }

export type ApplyStreamStartInput = { hostOverride: string | null }

/**
 * The signed-in nixmac account, minus any secret material.
 */
export type AuthAccount = { 
/**
 * Stable account identifier assigned by the server.
 */
id: string; 
/**
 * Account email address used to sign in.
 */
email: string }

/**
 * A billing product offered to customers, mirrored from `/api/billing/products`.
 */
export type BillingProductInfo = { product: string; name: string; currency: string; type: string; priceUsd?: number | null; recurringInterval?: string | null; minimumAmountUsd?: number | null; maximumAmountUsd?: number | null }

/**
 * Active Polar subscription mapped to a known nixmac product slug.
 */
export type BillingSubscription = { id: string; slug: string; productId: string; status: string }

/**
 * Hosted inference usage for the signed-in web account.
 */
export type BillingUsage = { currency: string; spentUsd: number }

export type BootstrapDefaultConfigInput = { hostname: string; templateId: string | null }

/**
 * Result of `darwin_build_check` — dry-run build outcome.
 */
export type BuildCheckResult = { 
/**
 * Whether the dry-run build passed.
 */
passed: boolean; 
/**
 * Build output or failure details.
 */
output: string }

export type Change = { id: number; hash: string; filename: string; diff: string; lineCount: number; createdAt: number; ownSummaryId: number }

export type ChangeSummary = { id: number; title: string; description: string; 
/**
 * One of `"QUEUED"`, `"DONE"`, `"FAILED"`, `"CANCELLED"`.
 */
status: string; createdAt: number }

export type ChangeWithSummary = { 
/**
 * Change row identifier.
 */
id: number; 
/**
 * Stable content hash for the change.
 */
hash: string; 
/**
 * Repository-relative changed file path.
 */
filename: string; 
/**
 * Unified diff content for this change.
 */
diff: string; 
/**
 * Number of lines in the change diff.
 */
lineCount: number; 
/**
 * Unix timestamp when the change was recorded.
 */
createdAt: number; 
/**
 * Direct summary row id assigned to this change, if any.
 */
ownSummaryId: number; 
/**
 * Summary title used for display.
 */
title: string; 
/**
 * Summary description used for display.
 */
description: string }

export type CheckoutInput = { product: string }

export type CheckoutUrl = { url: string }

export type Commit = { id: number; hash: string; treeHash: string; message: string | null; createdAt: number }

/**
 * Result of a successful `git_commit` command. State mirrors (git, evolve,
 * change map) flow through the `*_changed` events.
 */
export type CommitResult = { 
/**
 * Hash of the commit that was created.
 */
hash: string }

/**
 * Application configuration returned by `config_get`.
 */
export type Config = { 
/**
 * Absolute path to the selected nix-darwin flake/config directory.
 */
configDir: string; 
/**
 * Selected `darwinConfigurations.<host>` attribute, when configured.
 */
hostAttr: string | null }

/**
 * Result of a managed-edit apply operation (homebrew, system-defaults, etc.).
 */
export type ConfigEditApplyResult = { 
/**
 * Whether the config edit was applied.
 */
ok: boolean; 
/**
 * Number of items applied.
 */
count: number }

export type ConfigImportGithubInput = { repoRef: string; dirName: string | null }

export type ConfigImportZipInput = { zipPath: string; dirName: string | null }

export type ConfigSetDirInput = { dir: string }

export type ConfigSetHostAttrInput = { host: string }

/**
 * Evolution lifecycle state.
 */
export type EvolutionState = 
/**
 * Initial state before generation starts.
 */
"pending" | 
/**
 * Currently generating/processing.
 */
"loading" | 
/**
 * Generation complete, ready for review.
 */
"generated" | 
/**
 * Changes have been applied (darwin-rebuild ran).
 */
"applied" | 
/**
 * Changes have been committed.
 */
"committed" | 
/**
 * An error occurred.
 */
"failed" | 
/**
 * Agent responded conversationally without making any environment changes.
 */
"conversational" | 
/**
 * Evolution was stopped because a safety limit was reached
 * (iterations, build attempts, token budget, or stale progress).
 * Distinguishes "we cut it off" from "the agent finished" so
 * the eval harness can score runaways correctly.
 */
"limitReached"

export type EvolveAnswerInput = { answer: string }

/**
 * Acknowledgement from `darwin_evolve_cancel`.
 */
export type EvolveCancelResult = { 
/**
 * Whether the cancellation request was accepted.
 */
ok: boolean; 
/**
 * Human-readable cancellation result.
 */
message: string }

export type EvolveInput = { description: string }

/**
 * The evolve routing state as projected for the frontend: the owned
 * [`EvolveSession`] fields joined with the two derived values (`step`,
 * `committable`).
 * 
 * This is the wire/event type — it is computed by
 * `state::evolve_state::project` and is never persisted or treated as a
 * source of truth on its own. `step` and `committable` are always recomputed
 * from live build/git state, so a value of this type is only a snapshot.
 */
export type EvolveState = { 
/**
 * Active evolution database id.
 */
evolutionId: number | null; 
/**
 * Active changeset id for the current repo state.
 */
currentChangesetId: number | null; 
/**
 * Whether the current state has been successfully built and can be committed.
 */
committable: boolean; 
/**
 * Branch used to reset repo state on evolve failure.
 */
backupBranch: string | null; 
/**
 * Branch used to recover repo state during rollback.
 */
rollbackBranch: string | null; 
/**
 * Nix store path that should be reactivated during rollback.
 */
rollbackStorePath: string | null; 
/**
 * Changeset id associated with the rollback target.
 */
rollbackChangesetId: number | null; 
/**
 * UI step derived from the session plus live build/git state.
 */
step: EvolveStep; 
/**
 * Last terminal state observed for this routing session.
 */
lastEvolutionState?: EvolutionState | null }

/**
 * Widget step derived from `EvolveState` fields.
 */
export type EvolveStep = 
/**
 * Initial prompt entry state.
 */
"begin" | 
/**
 * AI evolution is in progress or ready for review.
 */
"evolve" | 
/**
 * Changes are built and ready to commit.
 */
"commit" | 
/**
 * User is manually editing generated changes.
 */
"manualEvolve" | 
/**
 * Manual changes are ready to commit.
 */
"manualCommit"

/**
 * HEAD content vs working-tree content for a file, used by the diff tab Monaco DiffEditor.
 */
export type FileDiffContents = { original: string; modified: string }

export type FinalizeRollbackInput = { storePath: string | null; changesetId: number | null }

export type FlakeExistsAtInput = { dir: string }

export type GenerateHistoryFromInput = { commitHash: string; number: number }

export type GitCommitFileInput = { filename: string; message: string }

export type GitCommitInput = { message: string }

export type GitDiscardFileInput = { filename: string }

export type GitFileDiffContentsInput = { filenames: string[] }

/**
 * Current state of a GitHub-first desktop bootstrap flow.
 */
export type GithubBootstrapState = 
/**
 * The browser OAuth/install flow has not finished yet.
 */
"pending" | 
/**
 * The server created/bound the Better Auth user and returned a device key.
 */
"complete" | 
/**
 * The server could not create an account from GitHub identity; use email OTP.
 */
"fallbackRequired" | 
/**
 * The state token expired or is no longer usable.
 */
"expired"

/**
 * Public bootstrap status returned to the frontend. Secret material returned by
 * the server is persisted natively and intentionally omitted from this type.
 */
export type GithubBootstrapStatus = { 
/**
 * Bootstrap lifecycle state for this browser flow.
 */
state: GithubBootstrapState; 
/**
 * True once the account is linked to a GitHub App installation.
 */
connected: boolean; 
/**
 * The connected GitHub login (for display), when known.
 */
login: string | null; 
/**
 * The linked installation id, when connected.
 */
installationId: number; 
/**
 * The Better Auth account created or bound by the server, when complete.
 */
account: AuthAccount | null; 
/**
 * Human-readable reason to show when email OTP fallback is needed.
 */
fallbackReason: string | null; 
/**
 * Server-requested polling interval in seconds (used for GitHub slow_down).
 */
pollIntervalSeconds: number | null }

export type GithubBootstrapStatusInput = { state: string }

/**
 * Result of starting a GitHub connection flow. Authenticated connections use
 * `install_url` as the GitHub App install URL; unauthenticated bootstrap uses
 * GitHub device OAuth and includes a user code to display.
 */
export type GithubConnectStart = { 
/**
 * GitHub URL to open in the user's browser.
 */
installUrl: string; 
/**
 * Opaque state bound to the account/server flow.
 */
state: string; 
/**
 * Device OAuth code the user must enter at `verification_uri`.
 */
userCode: string | null; 
/**
 * Device OAuth verification URL.
 */
verificationUri: string | null; 
/**
 * Seconds until the device code expires.
 */
expiresIn: number | null; 
/**
 * Minimum polling interval, in seconds.
 */
interval: number | null }

export type GithubImportInput = { repoRef: string; dirName: string | null }

/**
 * A repository the installation can access, returned by `github_list_repos`.
 */
export type GithubRepo = { 
/**
 * Repository owner login.
 */
owner: string; 
/**
 * Repository name.
 */
name: string; 
/**
 * Whether the repository is private.
 */
private: boolean; 
/**
 * ISO-8601 timestamp of the last update.
 */
updatedAt: string; 
/**
 * Default branch name (where `flake.nix` is checked).
 */
defaultBranch: string; 
/**
 * Whether a `flake.nix` exists at the default branch root.
 */
hasFlake: boolean }

/**
 * Whether this account has a linked GitHub App installation, returned by
 * `github_status` (polled while the browser install completes).
 */
export type GithubStatus = { 
/**
 * True once the account is linked to a GitHub App installation.
 */
connected: boolean; 
/**
 * The connected GitHub login (for display), when known.
 */
login: string | null; 
/**
 * The linked installation id, when connected.
 */
installationId: number }

export type HelperServiceStatus = { label: string; available: boolean; registered: boolean; authorized: boolean; socketAvailable: boolean; detail: string | null }

/**
 * A commit entry combining git log data, tag-derived flags, optional DB metadata, and raw diff changes.
 */
export type HistoryItem = { 
/**
 * Git commit hash represented by this history row.
 */
hash: string; 
/**
 * Commit message, if available from git or local metadata.
 */
message: string | null; 
/**
 * Commit timestamp.
 */
createdAt: number; 
/**
 * Whether this commit corresponds to the active build record.
 */
isBuilt: boolean; 
/**
 * Whether this commit is the configured base commit.
 */
isBase: boolean; 
/**
 * Whether this commit was created outside nixmac.
 */
isExternal: boolean; 
/**
 * Number of files changed in this commit.
 */
fileCount: number; 
/**
 * Matching persisted commit row, if one exists.
 */
commit: Commit | null; 
/**
 * Semantic summaries for this commit's changes.
 */
changeMap: SemanticChangeMap | null; 
/**
 * Change hashes without summaries.
 */
unsummarizedHashes: string[]; 
/**
 * Raw changes parsed for this history item.
 */
rawChanges: Change[]; 
/**
 * Message of the commit this entry originated from, for restore/orphan flows.
 */
originMessage: string | null; 
/**
 * Hash of the commit this entry originated from, for restore/orphan flows.
 */
originHash: string | null; 
/**
 * Whether this represents a restored build no longer on the visible branch.
 */
isOrphanedRestore: boolean; 
/**
 * Whether this history item has been undone by a later restore operation.
 */
isUndone: boolean }

/**
 * Current Homebrew package state detected on the machine.
 */
export type HomebrewState = { 
/**
 * Whether Homebrew is installed and discoverable.
 */
isInstalled: boolean; 
/**
 * Installed cask names.
 */
casks: string[]; 
/**
 * Installed formula names.
 */
brews: string[]; 
/**
 * Configured Homebrew tap names.
 */
taps: string[]; 
/**
 * Source used to collect the state, when known.
 */
source: string | null; 
/**
 * Unix timestamp when this state was last collected.
 */
lastChecked: number }

export type InstallSyncAgentInput = { config: SyncAgentLaunchConfig | null }

export type LaunchdItem = { 
/**
 * launchd Label
 */
label: string; scope: LaunchdItemType; 
/**
 * Suggested Nix attribute name.
 * Example: "redis"
 */
name: string; 
/**
 * Command and arguments to execute.
 */
programArguments: string[]; 
/**
 * Launch when loaded.
 */
runAtLoad: boolean; 
/**
 * Keep the service running.
 */
keepAlive: boolean; 
/**
 * Environment variables.
 */
environmentVariables: Partial<{ [key in string]: string }>; 
/**
 * Log file locations.
 */
standardOutPath: string | null; standardErrorPath: string | null; 
/**
 * Working directory, if specified.
 */
workingDirectory: string | null }

export type LaunchdItemType = "LaunchAgent" | "LaunchDaemon" | "LaunchdUserAgent"

/**
 * Generic acknowledgement returned by fire-and-forget commands.
 */
export type OkResult = { 
/**
 * True when the command completed successfully.
 */
ok: boolean }

export type PathExistsInput = { dir: string }

export type PathNormalizeInput = { input: string }

/**
 * State sent to the preview indicator window.
 */
export type PreviewIndicatorState = { 
/**
 * Whether the floating preview indicator should be visible.
 */
visible: boolean; 
/**
 * Summary text displayed in the indicator.
 */
summary: string | null; 
/**
 * Number of changed files represented by the indicator.
 */
filesChanged: number; 
/**
 * Added lines displayed in the indicator.
 */
additions: number | null; 
/**
 * Removed lines displayed in the indicator.
 */
deletions: number | null; 
/**
 * Whether the indicator should show a loading state.
 */
isLoading: boolean }

/**
 * Lifecycle status of the darwin-rebuild apply/activate streams.
 */
export type RebuildStatus = { 
/**
 * True while a rebuild stream is in flight.
 */
isRunning: boolean; 
/**
 * Outcome of the last finished run; `None` while running or never run.
 */
success: boolean | null; 
/**
 * Exit code of the last finished run.
 */
exitCode: number | null; 
/**
 * Error class of the last failed run.
 */
errorType: string | null; 
/**
 * Error message of the last failed run.
 */
errorMessage: string | null; 
/**
 * Whether the failure left the system untouched.
 */
systemUntouched: boolean | null }

export type RestoreTargetInput = { targetHash: string }

/**
 * Result returned from a rollback erase operation. Git/evolve state mirrors
 * flow through the `*_changed` events; this only carries the rollback target.
 */
export type RollbackResult = { 
/**
 * Store path to reactivate as part of the rollback flow.
 */
rollbackStorePath: string | null; 
/**
 * Changeset id associated with the rollback target.
 */
rollbackChangesetId: number | null }

export type SemanticChangeGroup = { 
/**
 * Shared summary describing the grouped changes.
 */
summary: ChangeSummary; 
/**
 * Changes that belong to this semantic group.
 */
changes: ChangeWithSummary[] }

export type SemanticChangeMap = { 
/**
 * Groups of changes that share a generated semantic summary.
 */
groups: SemanticChangeGroup[]; 
/**
 * Changes with their own summaries or no group membership.
 */
singles: ChangeWithSummary[]; 
/**
 * Hashes for changes that could not be summarized.
 */
unsummarizedHashes: string[] }

/**
 * Result returned when the config directory is set (typed or picked).
 * State mirrors (evolve state, git state, hosts) flow through the
 * `*_changed` events; this only carries genuine command results.
 */
export type SetDirResult = { 
/**
 * Selected absolute config directory.
 */
dir: string; 
/**
 * True when the selected directory differs from the previous one.
 */
changed: boolean }

export type SyncAgentLaunchConfig = { configDir: string | null; hostAttr: string | null; syncPull: boolean; unattendedApply: boolean; startIntervalSeconds: number | null }

export type SyncAgentStatus = { label: string; installed: boolean; loaded: boolean; plistPath: string; detail: string | null }

/**
 * A single macOS system default that differs from the factory value.
 */
export type SystemDefault = { 
/**
 * nix-darwin option path for this macOS default.
 */
nixKey: string; 
/**
 * Human-readable setting label.
 */
label: string; 
/**
 * UI grouping category.
 */
category: string; 
/**
 * Current value read from macOS defaults.
 */
currentValue: string; 
/**
 * Factory/default value used for comparison.
 */
defaultValue: string }

/**
 * Result of a full system defaults scan.
 */
export type SystemDefaultsScan = { 
/**
 * Defaults that differ from known factory values.
 */
defaults: SystemDefault[]; 
/**
 * Number of defaults keys scanned.
 */
totalScanned: number }

export type Procedures = {
  billing: {
    checkout: Client<Record<never, never>, CheckoutInput, CheckoutUrl, Error>
    portal: Client<Record<never, never>, void, CheckoutUrl, Error>
    products: Client<Record<never, never>, void, BillingProductInfo[], Error>
    state: Client<Record<never, never>, void, AccountBilling, Error>
  }
  config: {
    get: Client<Record<never, never>, void, Config, Error>
    getThisHostname: Client<Record<never, never>, void, string, Error>
    importGithub: Client<Record<never, never>, ConfigImportGithubInput, SetDirResult, Error>
    importZip: Client<Record<never, never>, ConfigImportZipInput, SetDirResult, Error>
    pickDir: Client<Record<never, never>, void, SetDirResult | null, Error>
    pickZip: Client<Record<never, never>, void, string | null, Error>
    prepareNewDir: Client<Record<never, never>, ConfigSetDirInput, SetDirResult, Error>
    setDir: Client<Record<never, never>, ConfigSetDirInput, SetDirResult, Error>
    setHostAttr: Client<Record<never, never>, ConfigSetHostAttrInput, OkResult, Error>
  }
  darwin: {
    abortRestore: Client<Record<never, never>, void, void, Error>
    activateStorePath: Client<Record<never, never>, ActivateStorePathInput, OkResult, Error>
    applyStreamStart: Client<Record<never, never>, ApplyStreamStartInput, OkResult, Error>
    buildCheck: Client<Record<never, never>, void, BuildCheckResult, Error>
    evolve: Client<Record<never, never>, EvolveInput, void, Error>
    evolveAnswer: Client<Record<never, never>, EvolveAnswerInput, OkResult, Error>
    evolveCancel: Client<Record<never, never>, void, EvolveCancelResult, Error>
    evolveFromManual: Client<Record<never, never>, void, AdoptManualChangesResult, Error>
    finalizeApply: Client<Record<never, never>, void, void, Error>
    finalizeRestore: Client<Record<never, never>, RestoreTargetInput, void, Error>
    finalizeRollback: Client<Record<never, never>, FinalizeRollbackInput, void, Error>
    helperRegister: Client<Record<never, never>, void, HelperServiceStatus, Error>
    helperStatus: Client<Record<never, never>, void, HelperServiceStatus, Error>
    helperUnregister: Client<Record<never, never>, void, HelperServiceStatus, Error>
    prepareRestore: Client<Record<never, never>, RestoreTargetInput, void, Error>
    rebuildStatus: Client<Record<never, never>, void, RebuildStatus, Error>
    rollbackErase: Client<Record<never, never>, void, RollbackResult, Error>
    syncAgentInstall: Client<Record<never, never>, InstallSyncAgentInput, SyncAgentStatus, Error>
    syncAgentStatus: Client<Record<never, never>, void, SyncAgentStatus, Error>
    syncAgentUninstall: Client<Record<never, never>, void, SyncAgentStatus, Error>
  }
  evolveState: {
    clear: Client<Record<never, never>, void, EvolveState, Error>
    get: Client<Record<never, never>, void, EvolveState, Error>
  }
  flake: {
    bootstrapDefault: Client<Record<never, never>, BootstrapDefaultConfigInput, void, Error>
    exists: Client<Record<never, never>, void, boolean, Error>
    existsAt: Client<Record<never, never>, FlakeExistsAtInput, boolean, Error>
  }
  git: {
    commit: Client<Record<never, never>, GitCommitInput, CommitResult, Error>
    commitFile: Client<Record<never, never>, GitCommitFileInput, CommitResult, Error>
    discardFile: Client<Record<never, never>, GitDiscardFileInput, OkResult, Error>
    fileDiffContents: Client<Record<never, never>, GitFileDiffContentsInput, Partial<{ [key in string]: FileDiffContents }>, Error>
  }
  github: {
    bootstrapStart: Client<Record<never, never>, void, GithubConnectStart, Error>
    bootstrapStatus: Client<Record<never, never>, GithubBootstrapStatusInput, GithubBootstrapStatus, Error>
    connectStart: Client<Record<never, never>, void, GithubConnectStart, Error>
    disconnect: Client<Record<never, never>, void, void, Error>
    import: Client<Record<never, never>, GithubImportInput, SetDirResult, Error>
    listRepos: Client<Record<never, never>, void, GithubRepo[], Error>
    status: Client<Record<never, never>, void, GithubStatus, Error>
  }
  history: {
    generateFrom: Client<Record<never, never>, GenerateHistoryFromInput, void, Error>
    get: Client<Record<never, never>, void, HistoryItem[], Error>
  }
  homebrew: {
    applyDiff: Client<Record<never, never>, ApplyDiffInput, ConfigEditApplyResult, Error>
    getStateDiff: Client<Record<never, never>, void, HomebrewState, Error>
  }
  launchd: {
    scanItems: Client<Record<never, never>, void, LaunchdItem[], Error>
  }
  path: {
    exists: Client<Record<never, never>, PathExistsInput, boolean, Error>
    normalize: Client<Record<never, never>, PathNormalizeInput, string, Error>
  }
  previewIndicator: {
    getState: Client<Record<never, never>, void, PreviewIndicatorState, Error>
    hide: Client<Record<never, never>, void, OkResult, Error>
    show: Client<Record<never, never>, void, OkResult, Error>
    update: Client<Record<never, never>, PreviewIndicatorState, OkResult, Error>
  }
  scanner: {
    scanDefaults: Client<Record<never, never>, void, SystemDefaultsScan, Error>
  }
  summarizedChanges: {
    findChangeMap: Client<Record<never, never>, void, SemanticChangeMap, Error>
    generateCommitMessage: Client<Record<never, never>, void, string, Error>
    getChangeMap: Client<Record<never, never>, void, SemanticChangeMap, Error>
    summarizeCurrent: Client<Record<never, never>, void, SemanticChangeMap, Error>
  }
}
