// GENERATED by Specta — DO NOT EDIT.
// Re-run: cargo run --example specta_gen_ts --features codegen (any cwd)
// Source: src-tauri/src/sqlite_types.rs

export type Change = { id: number; hash: string; filename: string; diff: string; lineCount: number; createdAt: number; ownSummaryId: number }

export type ChangeSummary = { id: number; title: string; description: string; 
/**
 * One of `"QUEUED"`, `"DONE"`, `"FAILED"`, `"CANCELLED"`.
 */
status: string; createdAt: number }

export type Evolution = { id: number; originBranch: string }

