// GENERATED by Specta — DO NOT EDIT.
// Re-run: cd apps/native/src-tauri && cargo run --example specta_gen_ts
// Source: src-tauri/src/shared_types/ (re-exported by shared_types.rs)

/**
 * Result of `darwin_build_check` — dry-run build outcome.
 */
export type BuildCheckResult = { 
/**
 * Whether the dry-run build passed.
 */
passed: boolean; 
/**
 * Build output or failure details.
 */
output: string }

export type Change = { id: number; hash: string; filename: string; diff: string; lineCount: number; createdAt: number; ownSummaryId: number | null }

/**
 * Groups Changes for a commit→base_commit pair. `commit_id` is NULL for speculative
 * (uncommitted) changesets. Membership is stored in the `set_changes` join table.
 */
export type ChangeSet = { id: number; commitId: number | null; baseCommitId: number; commitMessage: string | null; generatedCommitMessage: string | null; createdAt: number; evolutionId: number | null }

export type ChangeSummary = { id: number; title: string; description: string; 
/**
 * One of `"QUEUED"`, `"DONE"`, `"FAILED"`, `"CANCELLED"`.
 */
status: string; createdAt: number }

/**
 * Type of change for a file in git status.
 */
export type ChangeType = 
/**
 * File was added.
 */
"new" | 
/**
 * File contents changed.
 */
"edited" | 
/**
 * File was deleted.
 */
"removed" | 
/**
 * File was renamed or moved.
 */
"renamed"

export type ChangeWithSummary = { 
/**
 * Change row identifier.
 */
id: number; 
/**
 * Stable content hash for the change.
 */
hash: string; 
/**
 * Repository-relative changed file path.
 */
filename: string; 
/**
 * Unified diff content for this change.
 */
diff: string; 
/**
 * Number of lines in the change diff.
 */
lineCount: number; 
/**
 * Unix timestamp when the change was recorded.
 */
createdAt: number; 
/**
 * Direct summary row id assigned to this change, if any.
 */
ownSummaryId: number | null; 
/**
 * Summary title used for display.
 */
title: string; 
/**
 * Summary description used for display.
 */
description: string }

/**
 * Availability of known AI CLI tools.
 */
export type CliToolsState = { 
/**
 * Whether the Claude CLI is installed.
 */
claude: boolean; 
/**
 * Whether the Codex CLI is installed.
 */
codex: boolean; 
/**
 * Whether the OpenCode CLI is installed.
 */
opencode: boolean }

export type Commit = { id: number; hash: string; treeHash: string; message: string | null; createdAt: number }

/**
 * Result of a successful `git_commit` command.
 */
export type CommitResult = { 
/**
 * Hash of the commit that was created.
 */
hash: string; 
/**
 * Evolve state after committing.
 */
evolveState: EvolveState }

/**
 * Application configuration returned by `config_get`.
 */
export type Config = { 
/**
 * Absolute path to the selected nix-darwin flake/config directory.
 */
configDir: string; 
/**
 * Selected `darwinConfigurations.<host>` attribute, when configured.
 */
hostAttr: string | null }

/**
 * Payload for `config:changed`, when emitted by a filesystem watcher.
 */
export type ConfigChangedEvent = { 
/**
 * Whether the selected config currently has changes.
 */
hasChanges: boolean }

/**
 * Result of a managed-edit apply operation (homebrew, system-defaults, etc.).
 */
export type ConfigEditApplyResult = { 
/**
 * Whether the config edit was applied.
 */
ok: boolean; 
/**
 * Number of items applied.
 */
count: number; 
/**
 * Semantic summary after applying the edit.
 */
changeMap: SemanticChangeMap; 
/**
 * Git status after applying the edit.
 */
gitStatus: GitStatus; 
/**
 * Evolve routing state after applying the edit.
 */
evolveState: EvolveState }

/**
 * Per-field description rendered into a UI control.
 */
export type ConfigField = { 
/**
 * Key as written to the underlying store (typically camelCase).
 */
key: string; 
/**
 * Human-readable label rendered above the input.
 */
label: string; 
/**
 * Optional help text (rendered as a tooltip / "info" icon).
 */
help?: string | null; 
/**
 * What control to render.
 */
ty: FieldType; 
/**
 * Default if the store has no value yet.
 */
default: JsonValue; 
/**
 * Current value loaded from the store.
 */
current: JsonValue }

/**
 * One section in the auto-rendered settings panel — corresponds to one
 * `#[derive(Configurable)]` struct.
 */
export type ConfigurableSchema = { 
/**
 * Unique stable identifier (struct's Rust name). Used by `set_field` to
 * dispatch to the right registered configurable.
 */
name: string; 
/**
 * Title shown above the section in the UI.
 */
displayName: string; 
/**
 * Optional one-line description shown under the title.
 */
description?: string | null; fields: ConfigField[] }

/**
 * Payload for `darwin:apply:data`.
 */
export type DarwinApplyDataEvent = { 
/**
 * Raw output chunk from the rebuild process.
 */
chunk: string }

/**
 * Payload for `darwin:apply:end`.
 */
export type DarwinApplyEndEvent = { 
/**
 * Whether rebuild/apply completed successfully.
 */
ok: boolean; 
/**
 * Exit/status code for the rebuild/apply operation.
 */
code: number; 
/**
 * Error category on failure.
 */
error_type: RebuildErrorType | null; 
/**
 * Human-readable failure message.
 */
error: string | null; 
/**
 * Path to the captured rebuild log, when available.
 */
log_file: string | null }

/**
 * Payload for `darwin:apply:summary`.
 */
export type DarwinApplySummaryEvent = { 
/**
 * Human-readable summary text.
 */
text: string; 
/**
 * Whether this is the final summary event.
 */
complete: boolean | null; 
/**
 * Whether the rebuild succeeded.
 */
success: boolean | null; 
/**
 * Whether this event describes an error.
 */
error: boolean | null; 
/**
 * Error category when `error` or `complete && !success` is set.
 */
error_type: RebuildErrorType | null }

/**
 * Response from the debug Sentry event command.
 */
export type DebugSentryResult = { 
/**
 * Whether the debug event was sent.
 */
ok: boolean; 
/**
 * Human-readable result message.
 */
message: string }

export type EnumVariant = { value: string; label: string }

/**
 * Evolution failure payload with partial telemetry.
 */
export type EvolutionFailureResult = { 
/**
 * Error message returned to the frontend.
 */
error: string; 
/**
 * Best-effort git status captured after failure.
 */
gitStatus: GitStatus | null; 
/**
 * Partial telemetry captured before failure.
 */
telemetry: EvolutionTelemetry }

/**
 * Evolution result returned to the frontend on completion.
 */
export type EvolutionResult = { 
/**
 * Semantic summary of the generated changes.
 */
changeMap: SemanticChangeMap; 
/**
 * Git status after evolution completes.
 */
gitStatus: GitStatus; 
/**
 * Evolve routing state after evolution completes.
 */
evolveState: EvolveState; 
/**
 * Assistant response when no file changes were produced.
 */
conversationalResponse: string | null; 
/**
 * Telemetry collected during evolution.
 */
telemetry: EvolutionTelemetry }

/**
 * Evolution lifecycle state.
 */
export type EvolutionState = 
/**
 * Initial state before generation starts.
 */
"pending" | 
/**
 * Currently generating/processing.
 */
"loading" | 
/**
 * Generation complete, ready for review.
 */
"generated" | 
/**
 * Changes have been applied (darwin-rebuild ran).
 */
"applied" | 
/**
 * Changes have been committed.
 */
"committed" | 
/**
 * An error occurred.
 */
"failed" | 
/**
 * Agent responded conversationally without making any environment changes.
 */
"conversational"

/**
 * Telemetry counters from a completed evolution run.
 */
export type EvolutionTelemetry = { 
/**
 * Final lifecycle state for the evolution.
 */
state: EvolutionState; 
/**
 * Number of agent iterations completed.
 */
iterations: number; 
/**
 * Number of build attempts completed.
 */
buildAttempts: number; 
/**
 * Total token count reported by the provider.
 */
totalTokens: number; 
/**
 * Number of edit operations performed.
 */
editsCount: number; 
/**
 * Number of reasoning/thinking events observed.
 */
thinkingCount: number; 
/**
 * Number of tool calls performed.
 */
toolCallsCount: number; 
/**
 * Total evolution duration in milliseconds.
 */
durationMs: number }

/**
 * Acknowledgement from `darwin_evolve_cancel`.
 */
export type EvolveCancelResult = { 
/**
 * Whether the cancellation request was accepted.
 */
ok: boolean; 
/**
 * Human-readable cancellation result.
 */
message: string }

/**
 * Event type for streaming evolve progress updates.
 */
export type EvolveEvent = { 
/**
 * Raw log output or technical details for the event.
 */
raw: string; 
/**
 * Human-readable status text for rendering in the widget.
 */
summary: string; 
/**
 * Event category used by the UI timeline.
 */
eventType: EvolveEventType; 
/**
 * Agent iteration associated with the event, if applicable.
 */
iteration: number | null; 
/**
 * Milliseconds elapsed since the evolution started.
 */
timestampMs: number }

/**
 * Types of evolve events for UI rendering.
 */
export type EvolveEventType = 
/**
 * Evolution is starting.
 */
"start" | 
/**
 * Agent loop entered a new iteration.
 */
"iteration" | 
/**
 * Model reasoning/thinking content was observed.
 */
"thinking" | 
/**
 * Agent is reading a file.
 */
"reading" | "searchPackages" | 
/**
 * Agent is editing a file.
 */
"editing" | 
/**
 * Agent is running a build check.
 */
"buildCheck" | 
/**
 * Build check passed.
 */
"buildPass" | 
/**
 * Build check failed.
 */
"buildFail" | 
/**
 * Agent invoked a tool.
 */
"toolCall" | 
/**
 * Request was sent to an AI provider.
 */
"apiRequest" | 
/**
 * Response was received from an AI provider.
 */
"apiResponse" | 
/**
 * Evolution completed successfully.
 */
"complete" | 
/**
 * Evolution failed or emitted an error.
 */
"error" | 
/**
 * Informational event without a more specific category.
 */
"info" | 
/**
 * Change summarization is running.
 */
"summarizing" | 
/**
 * Agent asked the user for input.
 */
"question"

/**
 * Persisted evolve state stored in `evolve-state.json`.
 */
export type EvolveState = { 
/**
 * Active evolution database id.
 */
evolutionId: number | null; 
/**
 * Active changeset id for the current repo state.
 */
currentChangesetId: number | null; 
/**
 * Whether the current state has been successfully built and can be committed.
 */
committable: boolean; 
/**
 * Branch used to reset repo state on evolve failure.
 */
backupBranch: string | null; 
/**
 * Branch used to recover repo state during rollback.
 */
rollbackBranch: string | null; 
/**
 * Nix store path that should be reactivated during rollback.
 */
rollbackStorePath: string | null; 
/**
 * Changeset id associated with the rollback target.
 */
rollbackChangesetId: number | null; 
/**
 * UI step derived from the routing state.
 */
step: EvolveStep; 
/**
 * Last terminal state observed for this routing session.
 * 
 * This supports transition-sensitive behavior when returning to Begin
 * and maybe some other useful things in the future.
 */
lastEvolutionState?: EvolutionState | null }

/**
 * Widget step derived from `EvolveState` fields.
 */
export type EvolveStep = 
/**
 * Initial prompt entry state.
 */
"begin" | 
/**
 * AI evolution is in progress or ready for review.
 */
"evolve" | 
/**
 * Changes are built and ready to commit.
 */
"commit" | 
/**
 * User is manually editing generated changes.
 */
"manualEvolve" | 
/**
 * Manual changes are ready to commit.
 */
"manualCommit"

/**
 * Result of a successful settings export. Returned to the frontend so it can
 * show the file path and the count of skipped sensitive keys.
 */
export type ExportResult = { path: string; keysWritten: number; keysSkipped: string[] }

/**
 * AI provider/model info and usage signals.
 */
export type FeedbackAiProviderModelInfo = { 
/**
 * Provider used for evolution requests.
 */
evolveProvider: string | null; 
/**
 * Model used for evolution requests.
 */
evolveModel: string | null; 
/**
 * Provider used for summary requests.
 */
summaryProvider: string | null; 
/**
 * Model used for summary requests.
 */
summaryModel: string | null; 
/**
 * Token count reported for the related AI run.
 */
totalTokens: number | null; 
/**
 * Latency in milliseconds for the related AI run.
 */
latencyMs: number | null; 
/**
 * Iterations completed by the related evolution.
 */
iterations: number | null; 
/**
 * Build attempts completed by the related evolution.
 */
buildAttempts: number | null }

/**
 * Flake input metadata captured from flake.lock.
 */
export type FeedbackFlakeInputEntry = { 
/**
 * Git revision for the flake input.
 */
rev: string | null; 
/**
 * Flake input last-modified timestamp from `flake.lock`.
 */
lastModified: number | null; 
/**
 * Store hash for the locked input.
 */
narHash: string | null }

/**
 * Snapshot of selected flake inputs.
 */
export type FeedbackFlakeInputsSnapshot = { 
/**
 * Locked `nixpkgs` input metadata.
 */
nixpkgs: FeedbackFlakeInputEntry | null; 
/**
 * Locked `nix-darwin` input metadata.
 */
"nix-darwin": FeedbackFlakeInputEntry | null; 
/**
 * Locked `home-manager` input metadata.
 */
"home-manager": FeedbackFlakeInputEntry | null }

/**
 * Metadata collected for feedback submission based on user opt-in.
 */
export type FeedbackMetadata = { 
/**
 * Current frontend/store snapshot, represented as arbitrary JSON.
 */
currentAppStateSnapshot: JsonValue | null; 
/**
 * Runtime system information.
 */
systemInfo: FeedbackSystemInfo | null; 
/**
 * Aggregated local usage statistics.
 */
usageStats: FeedbackUsageStats | null; 
/**
 * Captured evolution log content.
 */
evolutionLogContent: string | null; 
/**
 * Diff for changed Nix files at submission time.
 */
changedNixFilesDiff: string | null; 
/**
 * AI provider/model metadata for the related run.
 */
aiProviderModelInfo: FeedbackAiProviderModelInfo | null; 
/**
 * Latest build error output.
 */
buildErrorOutput: string | null; 
/**
 * Selected locked flake input metadata.
 */
flakeInputsSnapshot: FeedbackFlakeInputsSnapshot | null; 
/**
 * Recent application log content.
 */
appLogsContent: string | null; 
/**
 * Panic details when feedback is submitted after a crash.
 */
panicDetails: FeedbackPanicDetails | null }

/**
 * Request payload for gathering feedback metadata.
 */
export type FeedbackMetadataRequest = { 
/**
 * Feedback category selected by the user.
 */
feedbackType: string; 
/**
 * User opt-in flags controlling which artifacts may be gathered.
 */
share: FeedbackShareOptions }

/**
 * Panic/crash information captured when a Rust panic occurs.
 */
export type FeedbackPanicDetails = { 
/**
 * Panic message captured by the panic hook.
 */
message: string; 
/**
 * Source location reported by Rust, when available.
 */
location: string | null; 
/**
 * Captured backtrace, when available.
 */
backtrace: string | null; 
/**
 * UTC timestamp when the panic was captured.
 */
timestamp: string }

/**
 * Options indicating which feedback artifacts the user allows sharing.
 */
export type FeedbackShareOptions = { 
/**
 * Include the current widget/store state snapshot.
 */
currentAppState: boolean; 
/**
 * Include OS, architecture, Nix, and app version details.
 */
systemInfo: boolean; 
/**
 * Include aggregated usage statistics.
 */
usageStats: boolean; 
/**
 * Include the active evolution log.
 */
evolutionLog: boolean; 
/**
 * Include the current diff for changed Nix files.
 */
changedNixFiles: boolean; 
/**
 * Include selected AI provider/model and usage details.
 */
aiProviderModelInfo: boolean; 
/**
 * Include the latest build error output, if any.
 */
buildErrorOutput: boolean; 
/**
 * Include selected `flake.lock` input metadata.
 */
flakeInputsSnapshot: boolean; 
/**
 * Include recent application logs.
 */
appLogs: boolean }

/**
 * System information captured from the runtime.
 */
export type FeedbackSystemInfo = { 
/**
 * Operating system name, e.g. `macOS`.
 */
osName: string | null; 
/**
 * Operating system version string.
 */
osVersion: string | null; 
/**
 * Hardware/system architecture, e.g. `aarch64-darwin`.
 */
arch: string | null; 
/**
 * Installed Nix version, when detected.
 */
nixVersion: string | null; 
/**
 * nixmac application version.
 */
appVersion: string | null }

/**
 * Aggregated usage stats for feedback.
 */
export type FeedbackUsageStats = { 
/**
 * Number of evolutions recorded locally.
 */
totalEvolutions: number | null; 
/**
 * Percentage of evolutions that completed successfully.
 */
successRate: number | null; 
/**
 * Average number of agent iterations per evolution.
 */
avgIterations: number | null; 
/**
 * Timestamp when the stats were computed.
 */
lastComputedAt: string | null; 
/**
 * Additional structured usage fields that are not part of the stable contract.
 */
extra: JsonValue | null }

/**
 * What kind of control should render this field.
 */
export type FieldType = 
/**
 * Numeric input with optional min/max/step.
 */
{ kind: "number"; min?: number | null; max?: number | null; step?: number | null } | 
/**
 * Toggle / checkbox.
 */
{ kind: "boolean" } | 
/**
 * Single-line text or multi-line textarea when `multiline = true`.
 */
{ kind: "string"; multiline: boolean } | 
/**
 * Select / dropdown of pre-declared options.
 */
{ kind: "enum"; variants: EnumVariant[] }

/**
 * HEAD content vs working-tree content for a file, used by the diff tab Monaco DiffEditor.
 */
export type FileDiffContents = { original: string; modified: string }

/**
 * Result of a successful `finalize_apply` or `finalize_rollback` command.
 */
export type FinalizeApplyResult = { 
/**
 * Git status after finalization.
 */
gitStatus: GitStatus; 
/**
 * Evolve state after finalization.
 */
evolveState: EvolveState }

/**
 * Individual file status parsed from diff headers.
 */
export type GitFileStatus = { 
/**
 * Repository-relative file path.
 */
path: string; 
/**
 * Parsed status category for this file.
 */
changeType: ChangeType }

/**
 * Latest git status slice emitted by the git status watcher.
 */
export type GitState = { 
/**
 * Latest git status snapshot, if it could be read.
 */
gitStatus: GitStatus | null; 
/**
 * True when a build outside nixmac was detected.
 */
externalBuildDetected: boolean }

/**
 * Comprehensive git repository status.
 */
export type GitStatus = { 
/**
 * Changed files parsed from git status/diff output.
 */
files: GitFileStatus[]; 
/**
 * Current branch name, when the repository has one checked out.
 */
branch: string | null; 
/**
 * Unified diff for the current working tree/index changes.
 */
diff: string; 
/**
 * Total added lines in `diff`.
 */
additions: number; 
/**
 * Total removed lines in `diff`.
 */
deletions: number; 
/**
 * Current HEAD commit hash, when available.
 */
headCommitHash: string | null; 
/**
 * Whether HEAD is known to be clean relative to tracked changes.
 */
cleanHead: boolean; 
/**
 * Raw change rows associated with the current diff.
 */
changes: Change[] }

/**
 * A commit entry combining git log data, tag-derived flags, optional DB metadata, and raw diff changes.
 */
export type HistoryItem = { 
/**
 * Git commit hash represented by this history row.
 */
hash: string; 
/**
 * Commit message, if available from git or local metadata.
 */
message: string | null; 
/**
 * Commit timestamp.
 */
createdAt: number; 
/**
 * Whether this commit corresponds to the active build record.
 */
isBuilt: boolean; 
/**
 * Whether this commit is the configured base commit.
 */
isBase: boolean; 
/**
 * Whether this commit was created outside nixmac.
 */
isExternal: boolean; 
/**
 * Number of files changed in this commit.
 */
fileCount: number; 
/**
 * Matching persisted commit row, if one exists.
 */
commit: Commit | null; 
/**
 * Semantic summaries for this commit's changes.
 */
changeMap: SemanticChangeMap | null; 
/**
 * Change hashes without summaries.
 */
unsummarizedHashes: string[]; 
/**
 * Raw changes parsed for this history item.
 */
rawChanges: Change[]; 
/**
 * Message of the commit this entry originated from, for restore/orphan flows.
 */
originMessage: string | null; 
/**
 * Hash of the commit this entry originated from, for restore/orphan flows.
 */
originHash: string | null; 
/**
 * Whether this represents a restored build no longer on the visible branch.
 */
isOrphanedRestore: boolean; 
/**
 * Whether this history item has been undone by a later restore operation.
 */
isUndone: boolean }

/**
 * Current Homebrew package state detected on the machine.
 */
export type HomebrewState = { 
/**
 * Whether Homebrew is installed and discoverable.
 */
isInstalled: boolean; 
/**
 * Installed cask names.
 */
casks: string[]; 
/**
 * Installed formula names.
 */
brews: string[]; 
/**
 * Configured Homebrew tap names.
 */
taps: string[]; 
/**
 * Source used to collect the state, when known.
 */
source: string | null; 
/**
 * Unix timestamp when this state was last collected.
 */
lastChecked: number }

/**
 * Result of a successful settings import.
 */
export type ImportResult = { path: string; keysImported: number }

export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>

/**
 * Result of `nix_check` — reports whether Nix and darwin-rebuild are available.
 */
export type NixCheckResult = { 
/**
 * Whether Nix is installed.
 */
installed: boolean; 
/**
 * Installed Nix version string, when available.
 */
version: string | null; 
/**
 * Whether `darwin-rebuild` is available.
 */
darwinRebuildAvailable: boolean }

/**
 * Payload for `nix:darwin-rebuild:end`.
 */
export type NixDarwinRebuildEndEvent = { 
/**
 * Whether nix-darwin setup completed successfully.
 */
ok: boolean; 
/**
 * Human-readable failure message.
 */
error: string | null }

/**
 * Payload for `nix:install:end`.
 */
export type NixInstallEndEvent = { 
/**
 * Whether setup completed successfully.
 */
ok: boolean; 
/**
 * Exit/status code for the completed setup phase.
 */
code: number; 
/**
 * Installed Nix version on success.
 */
nix_version: string | null; 
/**
 * Whether `darwin-rebuild` is available after setup.
 */
darwin_rebuild_available: boolean | null; 
/**
 * Failure category on error.
 */
error_type: NixInstallErrorType | null; 
/**
 * Human-readable failure message.
 */
error: string | null }

/**
 * Known Nix installation failure categories.
 */
export type NixInstallErrorType = 
/**
 * Unexpected internal error before a specific phase failed.
 */
"internal" | 
/**
 * Failed while downloading the installer package.
 */
"download_failed" | 
/**
 * The macOS installer failed or was cancelled.
 */
"installer_failed" | 
/**
 * A setup phase timed out.
 */
"timeout" | 
/**
 * nix-darwin prefetch/setup failed.
 */
"darwin_rebuild"

/**
 * Phase emitted during Nix installation/setup.
 */
export type NixInstallPhase = 
/**
 * Downloading the Determinate Nix installer package.
 */
"downloading" | 
/**
 * Waiting for the macOS installer UI to complete.
 */
"waiting-for-installer" | 
/**
 * Prefetching nix-darwin's `darwin-rebuild` command.
 */
"prefetching"

/**
 * Payload for `nix:install:progress`.
 */
export type NixInstallProgressEvent = { 
/**
 * Current setup phase.
 */
phase: NixInstallPhase; 
/**
 * Bytes downloaded so far, for download phase progress.
 */
downloaded: number | null; 
/**
 * Total bytes expected, when known.
 */
total: number | null }

/**
 * Generic acknowledgement returned by fire-and-forget commands.
 */
export type OkResult = { 
/**
 * True when the command completed successfully.
 */
ok: boolean }

/**
 * Individual permission state.
 */
export type Permission = { 
/**
 * Stable permission identifier.
 */
id: string; 
/**
 * Human-readable permission name.
 */
name: string; 
/**
 * Why nixmac needs this permission.
 */
description: string; 
/**
 * Whether onboarding requires this permission.
 */
required: boolean; 
/**
 * Whether the app can trigger the system prompt directly.
 */
canRequestProgrammatically: boolean; 
/**
 * Current permission status.
 */
status: PermissionStatus; 
/**
 * Manual instructions for permissions that cannot be requested programmatically.
 */
instructions?: string | null }

/**
 * Permission status.
 */
export type PermissionStatus = 
/**
 * Permission has been granted.
 */
"granted" | 
/**
 * Permission was checked and denied.
 */
"denied" | 
/**
 * Permission has not been resolved yet.
 */
"pending" | 
/**
 * Permission state could not be determined.
 */
"unknown"

/**
 * All permissions state.
 */
export type PermissionsState = { 
/**
 * Individual permission states.
 */
permissions: Permission[]; 
/**
 * True when every required permission is granted.
 */
allRequiredGranted: boolean; 
/**
 * Unix timestamp when permissions were last checked.
 */
checkedAt: number | null }

/**
 * State sent to the preview indicator window.
 */
export type PreviewIndicatorState = { 
/**
 * Whether the floating preview indicator should be visible.
 */
visible: boolean; 
/**
 * Summary text displayed in the indicator.
 */
summary: string | null; 
/**
 * Number of changed files represented by the indicator.
 */
filesChanged: number; 
/**
 * Added lines displayed in the indicator.
 */
additions: number | null; 
/**
 * Removed lines displayed in the indicator.
 */
deletions: number | null; 
/**
 * Whether the indicator should show a loading state.
 */
isLoading: boolean }

/**
 * Known rebuild/activation failure categories.
 */
export type RebuildErrorType = 
/**
 * Nix evaluation hit infinite recursion.
 */
"infinite_recursion" | 
/**
 * Nix evaluation failed.
 */
"evaluation_error" | 
/**
 * Build failed after evaluation.
 */
"build_error" | 
/**
 * Full Disk Access is missing for activation.
 */
"full_disk_access" | 
/**
 * User cancelled the privileged activation prompt.
 */
"user_cancelled" | 
/**
 * Administrator authorization failed.
 */
"authorization_denied" | 
/**
 * Fallback for uncategorized failures.
 */
"generic_error"

/**
 * A recommended prompt based on the user's current macOS settings.
 */
export type RecommendedPrompt = { 
/**
 * Stable prompt identifier.
 */
id: string; 
/**
 * Prompt text suggested to the user.
 */
promptText: string }

/**
 * Result returned from a rollback erase operation.
 */
export type RollbackResult = { 
/**
 * Git status after rollback preparation.
 */
gitStatus: GitStatus; 
/**
 * Evolve state after rollback preparation.
 */
evolveState: EvolveState; 
/**
 * Store path to reactivate as part of the rollback flow.
 */
rollbackStorePath: string | null; 
/**
 * Changeset id associated with the rollback target.
 */
rollbackChangesetId: number | null }

/**
 * Payload for `rust:panic`.
 */
export type RustPanicEvent = { 
/**
 * Panic message captured by the panic hook.
 */
message: string; 
/**
 * Source location reported by Rust, when available.
 */
location: string | null; 
/**
 * Captured backtrace, when available.
 */
backtrace: string | null; 
/**
 * UTC timestamp when the panic was captured.
 */
timestamp: string }

export type SemanticChangeGroup = { 
/**
 * Shared summary describing the grouped changes.
 */
summary: ChangeSummary; 
/**
 * Changes that belong to this semantic group.
 */
changes: ChangeWithSummary[] }

export type SemanticChangeMap = { 
/**
 * Groups of changes that share a generated semantic summary.
 */
groups: SemanticChangeGroup[]; 
/**
 * Changes with their own summaries or no group membership.
 */
singles: ChangeWithSummary[]; 
/**
 * Hashes for changes that could not be summarized.
 */
unsummarizedHashes: string[] }

/**
 * Result returned when the config directory is set (typed or picked).
 * `evolve_state` and `hosts` are `Some` only when the directory actually changed.
 */
export type SetDirResult = { 
/**
 * Selected absolute config directory.
 */
dir: string; 
/**
 * Fresh evolve state after changing directories, when applicable.
 */
evolveState: EvolveState | null; 
/**
 * Hosts discovered in the selected flake, when applicable.
 */
hosts: string[] | null }

export type SummarizedChange = { 
/**
 * Raw change row.
 */
change: Change; 
/**
 * Summary attached directly to this change.
 */
ownSummary: ChangeSummary | null; 
/**
 * Summary inherited from this change's group.
 */
groupSummary: ChangeSummary | null }

export type SummarizedChangeSet = { 
/**
 * Change set represented by this response.
 */
changeSet: ChangeSet; 
/**
 * Changes in the set with their available summaries.
 */
changes: SummarizedChange[]; 
/**
 * Change hashes expected in the set but missing from the database.
 */
missedHashes: string[] }

/**
 * A single macOS system default that differs from the factory value.
 */
export type SystemDefault = { 
/**
 * nix-darwin option path for this macOS default.
 */
nixKey: string; 
/**
 * Human-readable setting label.
 */
label: string; 
/**
 * UI grouping category.
 */
category: string; 
/**
 * Current value read from macOS defaults.
 */
currentValue: string; 
/**
 * Factory/default value used for comparison.
 */
defaultValue: string }

/**
 * Result of a full system defaults scan.
 */
export type SystemDefaultsScan = { 
/**
 * Defaults that differ from known factory values.
 */
defaults: SystemDefault[]; 
/**
 * Number of defaults keys scanned.
 */
totalScanned: number }

/**
 * User interface preferences (synced to settings.json via tauri-plugin-store).
 */
export type UiPrefs = { 
/**
 * OpenRouter API key stored in local app preferences.
 */
openrouterApiKey: string | null; 
/**
 * OpenAI API key stored in local app preferences.
 */
openaiApiKey: string | null; 
/**
 * Base URL for Ollama-compatible local models.
 */
ollamaApiBaseUrl: string | null; 
/**
 * Base URL for vLLM-compatible model servers.
 */
vllmApiBaseUrl: string | null; 
/**
 * API key for vLLM-compatible model servers.
 */
vllmApiKey: string | null; 
/**
 * Provider used for change summaries.
 */
summaryProvider: string | null; 
/**
 * Model used for change summaries.
 */
summaryModel: string | null; 
/**
 * Provider used for AI evolution.
 */
evolveProvider: string | null; 
/**
 * Model used for AI evolution.
 */
evolveModel: string | null; 
/**
 * Maximum agent iterations per evolution.
 */
maxIterations: number | null; 
/**
 * Maximum build attempts per evolution.
 */
maxBuildAttempts: number | null; 
/**
 * Whether diagnostic feedback may be sent.
 */
sendDiagnostics: boolean; 
/**
 * Whether to confirm before running build/apply.
 */
confirmBuild: boolean; 
/**
 * Whether to confirm before clearing changes.
 */
confirmClear: boolean; 
/**
 * Whether to confirm before rollback.
 */
confirmRollback: boolean; 
/**
 * Whether to auto-summarize changes when the app regains focus.
 */
autoSummarizeOnFocus: boolean; 
/**
 * Whether Homebrew state should be scanned on app startup.
 */
scanHomebrewOnStartup: boolean; 
/**
 * Whether the change view defaults to the Diff tab instead of Summary.
 */
defaultToDiffTab: boolean; 
/**
 * Whether developer-only UI/actions are enabled.
 */
developerMode: boolean; 
/**
 * Version pinned by the user, when update pinning is active.
 */
pinnedVersion: string | null; 
/**
 * Auto-update channel used when no explicit version pin is active.
 */
updateChannel: UpdateChannel }

/**
 * Partial update to UI preferences — every field is optional so the caller
 * can send only the fields they wish to change.
 */
export type UiPrefsUpdate = { 
/**
 * OpenRouter API key update.
 */
openrouterApiKey: string | null; 
/**
 * OpenAI API key update.
 */
openaiApiKey: string | null; 
/**
 * Evolution provider update.
 */
evolveProvider: string | null; 
/**
 * Evolution model update.
 */
evolveModel: string | null; 
/**
 * Summary provider update.
 */
summaryProvider: string | null; 
/**
 * Summary model update.
 */
summaryModel: string | null; 
/**
 * Maximum iteration count update.
 */
maxIterations: number | null; 
/**
 * Maximum build-attempt count update.
 */
maxBuildAttempts: number | null; 
/**
 * Ollama base URL update.
 */
ollamaApiBaseUrl: string | null; 
/**
 * vLLM base URL update.
 */
vllmApiBaseUrl: string | null; 
/**
 * vLLM API key update.
 */
vllmApiKey: string | null; 
/**
 * Diagnostics sharing preference update.
 */
sendDiagnostics: boolean | null; 
/**
 * Build confirmation preference update.
 */
confirmBuild: boolean | null; 
/**
 * Clear confirmation preference update.
 */
confirmClear: boolean | null; 
/**
 * Rollback confirmation preference update.
 */
confirmRollback: boolean | null; 
/**
 * Focus auto-summary preference update.
 */
autoSummarizeOnFocus: boolean | null; 
/**
 * Startup Homebrew scan preference update.
 */
scanHomebrewOnStartup: boolean | null; 
/**
 * Default-to-diff-tab preference update.
 */
defaultToDiffTab: boolean | null; 
/**
 * Developer mode preference update.
 */
developerMode: boolean | null; 
/**
 * `None` -> field not sent; `Some(None)` -> clear the pinned version.
 */
pinnedVersion?: string | null; 
/**
 * Auto-update channel preference update.
 */
updateChannel: UpdateChannel | null }

/**
 * Auto-update channel selected for release-mode builds.
 */
export type UpdateChannel = "stable" | "develop"

/**
 * Lightweight update metadata returned by the channel-aware updater command.
 */
export type UpdateInfo = { 
/**
 * Channel whose manifest produced this update.
 */
channel: UpdateChannel; 
/**
 * Version advertised by the channel manifest.
 */
version: string; 
/**
 * Release notes from the channel manifest, when available.
 */
notes: string | null }

