import type { SecretsVault } from "@/ipc/orpc-bindings";

/**
 * Demo fixture for Storybook — mirrors the reference design's data. No value
 * here is a real credential.
 */
export const MOCK_VAULT: SecretsVault = {
  primaryDecryptionIdentityId: "demo-mbp",
  agenixRulesFile: "secrets/secrets.nix",
  agenixDeclarationFile: "modules/darwin/agenix-secrets.nix",
  agenixEncryptedDirectoryFromDeclaration: "../../secrets",
  decryptionIdentities: [
    {
      kind: "sshKeyPath",
      locality: "configuration",
      path: "/etc/ssh/ssh_host_ed25519_key",
      available: true,
      publicKeys: ["age1qy8x0v4k2n7pq3wl9d0m5s8t1r6c4h2j"],
    },
    {
      kind: "ageKeyFile",
      locality: "process",
      path: "/Users/demo/.config/sops/age/keys.txt",
      available: true,
      publicKeys: [],
    },
  ],
  recipients: [
    {
      id: "demo-mbp",
      label: "Demo-MacBook-Pro",
      kind: "host",
      device: "This Mac",
      publicKey: "age1qy8x0v4k2n7pq3wl9d0m5s8t1r6c4h2j",
      keyType: "age",
      source: "sshHostKey",
      fingerprint: "SHA256:0f2a b7e4 … 9c1d",
      inUse: true,
      registrations: [
        { backend: "agenix", file: "secrets/secrets.nix" },
        { backend: "sops", file: ".sops.yaml" },
      ],
    },
    {
      id: "work-mini",
      label: "work-mac-mini",
      kind: "host",
      device: "Mac mini · office",
      publicKey: "age1ld0k2r7m4s9pqx3v6n8t1w5c2h4j7q0",
      keyType: "age",
      source: "sshHostKey",
      fingerprint: "SHA256:77b1 3ac9 … 4e02",
      inUse: true,
      registrations: [
        { backend: "agenix", file: "secrets/secrets.nix" },
        { backend: "sops", file: ".sops.yaml" },
      ],
    },
    {
      id: "yubikey",
      label: "yubikey-personal",
      kind: "user",
      device: "FIDO2 · age-plugin-yubikey",
      publicKey: "age1yubikey1qw8x3v0k2m7n4p9s6t1r5c2",
      keyType: "age",
      source: "yubikey",
      fingerprint: "SHA256:a3c9 12ff … 1f88",
      inUse: true,
      registrations: [{ backend: "agenix", file: "secrets/secrets.nix" }],
    },
    {
      id: "framework",
      label: "framework-13",
      kind: "host",
      device: "NixOS · staged, not committed",
      publicKey: "age1f3w9d2z0k8rql5m7n4p6s1t3v2c9h0j",
      keyType: "age",
      source: "sshHostKey",
      fingerprint: "SHA256:b8e0 44ad … 9a15",
      inUse: false,
      registrations: [],
    },
  ],
  entries: [
    {
      id: "github-token",
      name: "github-token",
      backend: "agenix",
      file: "secrets/github-token.age",
      publicRecipients: [
        "age1qy8x0v4k2n7pq3wl9d0m5s8t1r6c4h2j",
        "age1ld0k2r7m4s9pqx3v6n8t1w5c2h4j7q0",
      ],
      publicRecipientsResolved: true,
      recipientIds: ["demo-mbp", "work-mini"],
      decryptionCapability: "available",
      sopsKey: null,
    },
    {
      id: "tailscale-authkey",
      name: "tailscale-authkey",
      backend: "agenix",
      file: "secrets/tailscale.age",
      publicRecipients: ["age1qy8x0v4k2n7pq3wl9d0m5s8t1r6c4h2j"],
      publicRecipientsResolved: true,
      recipientIds: ["demo-mbp"],
      decryptionCapability: "available",
      sopsKey: null,
    },
    {
      id: "anthropic-api-key",
      name: "anthropic-api-key",
      backend: "agenix",
      file: "secrets/anthropic.age",
      publicRecipients: [
        "age1qy8x0v4k2n7pq3wl9d0m5s8t1r6c4h2j",
        "age1yubikey1qw8x3v0k2m7n4p9s6t1r5c2",
      ],
      publicRecipientsResolved: true,
      recipientIds: ["demo-mbp", "yubikey"],
      decryptionCapability: "available",
      sopsKey: null,
    },
    {
      id: "wifi-password",
      name: "wifi_password",
      backend: "sops",
      file: "secrets/network.yaml",
      sopsKey: "wifi_password",
      publicRecipients: [
        "age1qy8x0v4k2n7pq3wl9d0m5s8t1r6c4h2j",
        "age1ld0k2r7m4s9pqx3v6n8t1w5c2h4j7q0",
      ],
      publicRecipientsResolved: true,
      recipientIds: ["demo-mbp", "work-mini"],
      decryptionCapability: "available",
    },
    {
      id: "cachix-signing-key",
      name: "cachix_signing_key",
      backend: "sops",
      file: "secrets/cachix.yaml",
      sopsKey: "signing_key",
      publicRecipients: ["age1ld0k2r7m4s9pqx3v6n8t1w5c2h4j7q0"],
      publicRecipientsResolved: true,
      recipientIds: ["work-mini"],
      decryptionCapability: "unknown",
    },
  ],
};
