//! Tauri commands that walk the `configurable` inventory registry.
//!
//! Frontend calls `dev_configs_list` to enumerate every `#[derive(Configurable)]`
//! struct in the codebase, get its schema (labels, types, ranges, current
//! values), and render a section per struct. Edits go back through
//! `dev_config_set` which dispatches by struct name to the right shim
//! generated by the derive.

use super::helpers::capture_err;
use configurable::ConfigurableSchema;
use tauri::AppHandle;

/// Enumerate every registered Configurable struct with its current values.
#[tauri::command]
pub async fn dev_configs_list(app: AppHandle) -> Result<Vec<ConfigurableSchema>, String> {
    configurable::all_schemas(&app).map_err(|e| capture_err("dev_configs_list", e))
}

/// Set one field on one Configurable struct, dispatched by struct name.
#[tauri::command]
pub async fn dev_config_set(
    app: AppHandle,
    struct_name: String,
    key: String,
    value: serde_json::Value,
) -> Result<(), String> {
    configurable::set_field_by_name(&app, &struct_name, &key, value)
        .map_err(|e| capture_err("dev_config_set", e))
}
