#!/usr/bin/env python3

"""Build browsable markdown option docs from nixosOptionsDoc options JSON."""

from __future__ import annotations

import argparse
import json
import os
import shutil
from collections import defaultdict
from pathlib import Path
from typing import Any


AUTO_GENERATED_NOTICE = (
    "<!-- AUTO-GENERATED by scripts/nix-options.sh. Do not edit by hand. -->"
)


def sanitize(key: str) -> str:
    return key.replace("/", "_")


def md_cell(value: Any) -> str:
    if value is None:
        return ""
    if not isinstance(value, str):
        value = json.dumps(value, ensure_ascii=False)
    return value.replace("\n", " ").replace("|", "\\|").strip()


def option_type(options: dict[str, Any], path: str) -> str:
    return options.get(path, {}).get("type") or ""


def option_summary(options: dict[str, Any], path: str) -> str:
    return options.get(path, {}).get("description") or ""


def group_key(path: str, split_keys: set[str]) -> tuple[str, ...]:
    parts = path.split(".")
    if not parts or not parts[0]:
        return ("index",)
    if parts[0] in split_keys and len(parts) >= 2:
        return (parts[0], parts[1])
    return (parts[0],)


def describe(paths: list[str]) -> str:
    total = len(paths)
    return f"{total} option{'' if total == 1 else 's'}"


def write_options_file(
    options: dict[str, Any], paths: list[str], dotted_path: str, file_path: Path
) -> None:
    lines = [
        f"# {dotted_path}",
        "",
        AUTO_GENERATED_NOTICE,
        "",
        f"All options under `{dotted_path}`.",
        "",
        "| Option | Type | Description |",
        "| --- | --- | --- |",
    ]
    for path in sorted(paths):
        opt_type = option_type(options, path)
        type_cell = f"`{opt_type}`" if opt_type else ""
        lines.append(
            f"| `{path}` | {md_cell(type_cell)} | {md_cell(option_summary(options, path))} |"
        )
    lines.append("")
    file_path.write_text("\n".join(lines), encoding="utf-8")


def write_index(title: str, intro: str, rows: list[str], file_path: Path) -> None:
    lines = [
        f"# {title}",
        "",
        AUTO_GENERATED_NOTICE,
        "",
        intro,
        "",
        "| Key | Type | Description |",
        "| --- | --- | --- |",
    ]
    lines.extend(rows)
    lines.append("")
    file_path.write_text("\n".join(lines), encoding="utf-8")


def build_tree(name: str, options_file: Path, out_dir: Path, split_keys: set[str]) -> None:
    with options_file.open("r", encoding="utf-8") as f:
        options = json.load(f)

    groups: defaultdict[tuple[str, ...], list[str]] = defaultdict(list)
    top_level: defaultdict[str, list[str]] = defaultdict(list)
    for path in sorted(options):
        key = group_key(path, split_keys)
        groups[key].append(path)
        top_level[key[0]].append(path)

    if out_dir.exists():
        shutil.rmtree(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    index_rows = []
    for key in sorted(top_level):
        paths = top_level[key]
        safe = sanitize(key)
        if key in split_keys:
            sub_dir = out_dir / safe
            sub_dir.mkdir(parents=True, exist_ok=True)
            rows = []
            subkeys = sorted(k[1] for k in groups if len(k) == 2 and k[0] == key)
            for subkey in subkeys:
                sub_paths = groups[(key, subkey)]
                sub_safe = sanitize(subkey)
                write_options_file(
                    options,
                    sub_paths,
                    f"{key}.{subkey}",
                    sub_dir / f"{sub_safe}.md",
                )
                rows.append(
                    f"| [`{subkey}`]({sub_safe}.md) | category | {md_cell(describe(sub_paths))} |"
                )
            if (key,) in groups:
                own_paths = groups[(key,)]
                write_options_file(options, own_paths, key, sub_dir / "_self.md")
                rows.insert(
                    0,
                    f"| [`{key}`](_self.md) | category | {md_cell(describe(own_paths))} |",
                )
            write_index(key, f"Subcategories of `{key}`.", rows, sub_dir / "index.md")
            index_rows.append(
                f"| [`{key}`]({safe}/index.md) | category | {md_cell(describe(paths))} |"
            )
        else:
            write_options_file(options, paths, key, out_dir / f"{safe}.md")
            index_rows.append(
                f"| [`{key}`]({safe}.md) | category | {md_cell(describe(paths))} |"
            )

    write_index(
        name,
        f"Top-level option categories for `{name}`.",
        index_rows,
        out_dir / "index.md",
    )
    print(f"  {out_dir}")


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate markdown option docs from nixosOptionsDoc options JSON."
    )
    parser.add_argument("name")
    parser.add_argument("options_file", type=Path)
    parser.add_argument("out_dir", type=Path)
    parser.add_argument("split_keys", nargs="*", default=["programs", "services"])
    args = parser.parse_args()

    build_tree(args.name, args.options_file, args.out_dir, set(args.split_keys))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
