import type { StarterPromptIconName } from "@/components/widget/promptinput/starter-prompts";
import {
  BookOpen,
  Brush,
  Cable,
  Code2,
  FileKey,
  Focus,
  Gamepad2,
  Joystick,
  Keyboard,
  KeyRound,
  Network,
  NotebookText,
  Palette,
  PanelsTopLeft,
  Plane,
  Presentation,
  Radio,
  RefreshCcw,
  Server,
  ShieldCheck,
  Terminal,
  Video,
  Wifi,
  Wrench,
  type LucideIcon,
} from "lucide-react";

/** Maps the icon names used in `starter-prompts.json` to Lucide components. */
export const STARTER_PROMPT_ICON_COMPONENTS: Record<StarterPromptIconName, LucideIcon> = {
  "book-open": BookOpen,
  brush: Brush,
  cable: Cable,
  "code-2": Code2,
  "file-key": FileKey,
  focus: Focus,
  "gamepad-2": Gamepad2,
  joystick: Joystick,
  keyboard: Keyboard,
  "key-round": KeyRound,
  network: Network,
  "notebook-text": NotebookText,
  palette: Palette,
  "panels-top-left": PanelsTopLeft,
  plane: Plane,
  presentation: Presentation,
  radio: Radio,
  "refresh-ccw": RefreshCcw,
  server: Server,
  "shield-check": ShieldCheck,
  terminal: Terminal,
  video: Video,
  wifi: Wifi,
  wrench: Wrench,
};
