//! Configurable — store-backed dev settings without per-knob boilerplate.
//!
//! Derive `Configurable` on a struct to generate a `load(app)` method that reads
//! each field from `tauri-plugin-store`, falling back to the per-field default.
//! Edits made by the user via the dev-settings UI (which writes to the same
//! store keys) are picked up on the next `load(app)` call — i.e. hot-reload.
//!
//! ```ignore
//! use configurable::Configurable;
//!
//! #[derive(Configurable, Debug, Clone)]
//! #[config(store_path = "settings.json")]
//! pub struct EvolutionLimits {
//!     #[config(default = 25, key = "maxIterations")]
//!     pub max_iterations: usize,
//!
//!     #[config(default = 5, key = "maxBuildAttempts")]
//!     pub max_build_attempts: usize,
//! }
//!
//! let limits = EvolutionLimits::load(&app)?;
//! ```

use anyhow::Result;
use serde::de::DeserializeOwned;
use tauri::{AppHandle, Runtime};
use tauri_plugin_store::StoreExt;

pub use configurable_derive::Configurable;

/// Read a typed field from the named store, returning `None` when the key is
/// absent or the stored JSON fails to deserialize into `T` (e.g. schema drift).
/// Used by the code generated by `#[derive(Configurable)]`.
pub fn read_field<R, T>(app: &AppHandle<R>, store_path: &str, key: &str) -> Result<Option<T>>
where
    R: Runtime,
    T: DeserializeOwned,
{
    let store = app.store(store_path)?;
    Ok(store
        .get(key)
        .and_then(|value| serde_json::from_value(value.clone()).ok()))
}
